import pathlib
root=pathlib.Path(__file__).resolve().parents[3]
notices={
 'CURRENT_STATE.md':'> **Package v2 Phase 3 — 07/10/2026:** Theo mandate Bảo, package gửi Vy đã dựng thành [thư mục thường](deliverables/manager-package-v2/2026-10-07/BAT_DAU.html): đề xuất/mail xưng tên Bảo–Vy,3điểm góp ý về đầu tư, demo/thư viện17luồng VN/OSAT FDI với170PNG main-approved giữ nguyên byte,17reader và workbook2tab. **PHASE3_PREPARED / BAO_FINAL_REVIEW_PENDING**. [Hồ sơ Phase3](operations/manager-package-v2/phase3/README.md) giữ fresh anchor/binding, actual desktop/mobile và formula checks; integrity/operator records nằm ngoài gói gửi Vy. Cap11,7triệu chưa thuế, dashboard/kế toán và tuần1→review→tuần2 giữ nguyên. Phase1 checkpoint local4030d40; Phase2/3 là working files, chưa commit/main/GitHub. Không gửi mail/live/gen mới hoặc đổi frozen scopes; không nâng acceptance/technical state của artifact nguồn. Các notice Phase1/2 bên dưới là snapshot trước mandate Phase3.',
 'operations/LinkedIn_Current_Progress_2026-10-07.md':'> **Package v2 Phase 3 — current in package checkout, 07/10:** Bảo yêu cầu làm Phase3, gửi Vy và xưng tên. [Package current](../deliverables/manager-package-v2/2026-10-07/BAT_DAU.html) gồm business proposal/mail,3điểm góp ý, demo/thư viện17luồng VN/OSAT,170PNG giữ nguyên byte,17reader và workbook2tab; **PHASE3_PREPARED / BAO_FINAL_REVIEW_PENDING**. [Review/binding nội bộ](manager-package-v2/phase3/README.md) nằm ngoài deliverable. Actual170desktop card states và17mobile journeys/reader-return đã kiểm,15workbook checks; đây là package-surface review, không retro-upgrade source technical/live acceptance. Cap/chưa thuế/dashboard/cadence giữ nguyên. Phase1 commit4030d40, Phase2/3 local working files chưa commit/main/GitHub; main/source lanes và frozen scopes không đổi. Phase1/2 notices/receipts bên dưới là snapshot.',
 'operations/manager-package-v2/Package_V2_Three_Phase_Plan_2026-10-07.md':'> **Phase 3 current 07/10:** Bảo yêu cầu chuyển sang Phase3 từ bản split Phase2 và gửi Vy, xưng tên Bảo–Vy. [Package thư mục thường](../../deliverables/manager-package-v2/2026-10-07/BAT_DAU.html) đã dựng; **PHASE3_PREPARED / BAO_FINAL_REVIEW_PENDING**. Proposal/mail,3điểm đầu tư, demo/library/readers/workbook và actual source/render/formula reviews ghi tại [Phase3](phase3/README.md). Phase1 checkpoint4030d40; Phase2/3 là working files local. Main/push/live, email transmission và acceptance cuối giữ mandate riêng.',
 'operations/manager-package-v2/README.md':'> **Current — Phase3 prepared, 07/10:** Theo mandate mới của Bảo, [package gửi Vy](../../deliverables/manager-package-v2/2026-10-07/BAT_DAU.html) đã dựng trong thư mục thường, dùng xưng tên Bảo–Vy. **PHASE3_PREPARED / BAO_FINAL_REVIEW_PENDING**; xem [hồ sơ Phase3](phase3/README.md). Phase1 checkpoint4030d40; Phase2/3 là working changes local, chưa commit/main/GitHub. Phase1/2 records là historical baseline; không suy Vy đã phản hồi hoặc PO final acceptance.'
}
for path,notice in notices.items():
 p=root/path; body=p.read_text(encoding='utf-8'); lines=body.splitlines()
 assert lines[0].startswith('> **'),path
 lines[0]=notice; body='\n'.join(lines)+'\n'
 if path.endswith('Package_V2_Three_Phase_Plan_2026-10-07.md'):
  start=body.index('Trạng thái hiện tại:'); end=body.index('\n\n',start)
  body=body[:start]+'Trạng thái hiện tại: **PHASE3_PREPARED / BAO_FINAL_REVIEW_PENDING**. Plan checkpoint7796bc6 và Phase1 checkpoint4030d40 giữ nguyên. Bảo cho phép dùng bản split/3câu Phase2 để làm Phase3; recipient là Vy, xưng tên. Không có response thay Vy/lãnh đạo. Khi plan được lập ban đầu, ba phase chưa thực thi. Workflow/inventory vẫn là source contract, không số câu hỏi.'+body[end:]
  body=body.replace('Mandate hiện tại kích hoạt Phase 2 draft/offline, không thay quyết định budget hiện hành.','Mandate hiện tại kích hoạt Phase3 offline package construction, không thay quyết định budget hiện hành.')
  old='Docs impact tại checkpoint plan và Phase 1 giữ trong Git/source records.'
  start=body.index(old)
  body=body[:start]+'Docs impact tại checkpoint plan và Phase1 giữ trong Git/source records. Phase2 split/3questions là historical baseline cho mandate Phase3. Phase3 package/current-state/progress/owned README đã sync ở checkout riêng; historical Phase1/2 receipts giữ nguyên. Business/anchor/cap/cadence và frozen scopes không đổi. Bảo final review còn pending; main merge/push/live/email transmission giữ mandate riêng.\n'
 if path.endswith('manager-package-v2/README.md'):
  start=body.index('- Trạng thái:'); end=body.index('\n\n',start)
  body=body[:start]+'- Trạng thái: **PHASE3_PREPARED / BAO_FINAL_REVIEW_PENDING**. Inventory5738a1c, workflow823cc8b, plan7796bc6 và Phase1 revision1.2 checkpoint4030d40 là local history. [Phase2](phase2/README.md) giữ split40data/34items/S1–S10 và3câu ở snapshot trước. [Phase3](phase3/README.md) là current delivery/review record; recipient Vy, names in email. No new commit/main/push/live or answer from Vy.'+body[end:]
  body=body.replace('Sitemap/demo/library/workbook/export final giữ cho Phase 3 sau split review.','Phase3 đã dựng sitemap/demo/library/readers/workbook và polished mail/proposal; records Phase2 giữ nguyên như baseline lịch sử.')
  body=body.replace('Phạm vi writer Phase 2:', 'Historical writer scope Phase2:')
 p.write_text(body,encoding='utf-8',newline='\n')
print('Updated four owned current-state entrypoints; historical Phase1/2 bytes untouched.')
