"""Persist actual partial B13 review folder; no generated placeholders or ZIP."""
from prepare_draft import *
import html,shutil
OUT=ROOT/'deliverables/linkedin-safe-batches/parallel-fabless-2026-10-07/B13-en-f1-v1'
OUT.mkdir(parents=True,exist_ok=True);(OUT/'assets').mkdir(exist_ok=True)
plan=load(BASE+'/dispatch-plan.json');fixes=load(BASE+'/corrective-dispatch-plan.json');attempts=load(BASE+'/attempt-ledger.json')['attempts'];jobs={j['card_id']:j for j in plan['calls']}
jobs.update({j['card_id']:j for j in fixes['calls']});cards=[];pins=[];prompts=[]
for stage in ['cold','explanation','proof']:
 ad=load(BASE+'/'+stage+'/public-copy.json')['ads'][0]
 for x in ad['cards']:
  j=jobs[x['card_id']];src=ROOT/j['output_path'];image=None
  if src.is_file():
   dest=OUT/'assets'/(str(len(cards)+1).zfill(2)+'-'+x['card_id'].lower()+'.png');shutil.copyfile(src,dest);assert sha(j['output_path'])==hashlib.sha256(dest.read_bytes()).hexdigest();image=dest.relative_to(OUT).as_posix();pins.append(dict(card_id=x['card_id'],path=dest.relative_to(ROOT).as_posix(),sha256=sha(j['output_path']),source=j['output_path'],selected_corrective='_corrective1' in j['call_id']))
  cards.append(dict(x,stage=stage,caption=ad['caption'],image=image,status='CHANGES_REQUIRED' if x['card_id']=='RMK-BRIGHT-1' else 'GENERATED_REVIEW_PENDING' if image else 'NOT_GENERATED_BATCH_HOLD'))
  s=load(j['folder']+'/spec.json');call=next(z for z in s['calls'] if z['call_id']==j['call_id']);prompts.append(dict(card_id=x['card_id'],call_id=j['call_id'],prompt=call['prompt'],prompt_sha256=call['prompt_sha256'],referenced_image_paths=[r['path'] for r in call['references']],generated=image is not None,reused=False))
put(OUT.relative_to(ROOT).as_posix()+'/selected-copy.json',dict(revision='b13-review-copy-v1',cards=cards));put(OUT.relative_to(ROOT).as_posix()+'/selected-prompts.json',dict(revision='b13-review-prompts-v1',tool='built-in image_gen',calls=prompts))
style='''<style>*{box-sizing:border-box}body{font:16px/1.5 Arial,sans-serif;background:#f4f7fc;color:#0b132b;margin:0}main{max-width:960px;margin:auto;padding:20px}h1{font-size:26px;margin:0 0 8px}h2{font-size:22px}button,a{font:inherit}button{padding:8px 13px;background:white;color:#143255;border:1px solid #bccce2;border-radius:8px;cursor:pointer}button[aria-pressed=true]{background:#0052ff;color:white}nav{display:flex;flex-wrap:wrap;gap:6px;margin:12px 0}.notice{padding:12px;border-left:4px solid #b87912;background:#fff2d5;font-size:14px}article{max-width:680px;margin:18px auto;background:white;border:1px solid #dbe4ef;border-radius:12px;padding:18px}#ad{padding:0;overflow:hidden;width:min(640px,100%)}#caption,#native{padding:12px;margin:0}#art{display:block;width:100%;height:auto}#native{font-weight:bold}.feed #ad{width:min(333px,100%)}#missing{padding:20px;background:#fff2d5}details{max-width:680px;margin:20px auto}pre{white-space:pre-wrap;overflow-wrap:anywhere}a{color:#0052ba}p,li{overflow-wrap:anywhere}.entity{font-weight:bold;font-size:21px}.source{border-left:3px solid #0052ff;padding-left:12px}@media(max-width:500px){main{padding:12px}h1{font-size:22px}article{padding:14px}}</style>'''
head='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
data=json.dumps(cards,ensure_ascii=False).replace('</','<\\/')
viewer=head+'<title>B13 · Outsourced chip operations · English</title>'+style+'''<main><h1>B13 · Outsourced-production journey</h1><p>FDI English · Fabless Operations / SCM</p><div class="notice">HOLD / CHANGES_REQUIRED · 8 of 10 artwork units generated. Case card 1 needs a source-size correction; the batch has reached its two-correction cap. Case cards 3–4 have reviewed scripts but no generated artwork.</div><nav aria-label="Display size"><button id="desktop" aria-pressed="true">Desktop</button><button id="feed" aria-pressed="false">Feed333px</button></nav><nav id="cards" aria-label="Select card"></nav><h2 id="stage"></h2><article id="ad"><p id="caption"></p><img id="art" alt=""><div id="missing" hidden></div><p id="native"></p></article><nav aria-label="Journey controls"><button id="prev">Previous</button><span id="counter"></span><button id="next">Next</button><a href="case-reader.html">Read the China case summary</a></nav><details><summary>Inspect reviewed script</summary><pre id="script"></pre></details></main><script>const data='''+data+''';let pos=0;const q=id=>document.getElementById(id);data.forEach((x,i)=>{const b=document.createElement('button');b.textContent=i+1;b.setAttribute('aria-label','Card '+(i+1));b.onclick=()=>show(i);q('cards').append(b)});function show(i){pos=i;const x=data[i];q('stage').textContent=x.stage+' · '+x.card_id;q('caption').textContent=x.caption;q('art').hidden=!x.image;q('art').style.display=x.image?'block':'none';if(x.image){q('art').src=x.image;q('art').alt=x.alt}else{q('art').removeAttribute('src');q('art').alt=''}q('missing').hidden=!!x.image;q('missing').textContent='Artwork not generated: batch HOLD. Reviewed script: '+x.headline+' '+x.body;q('native').textContent=x.native_headline;q('counter').textContent=(i+1)+' / '+data.length;q('prev').disabled=i===0;q('next').disabled=i===data.length-1;q('script').textContent=JSON.stringify(x,null,2);Array.from(q('cards').children).forEach((b,k)=>b.setAttribute('aria-pressed',String(k===i)))}q('prev').onclick=()=>show(pos-1);q('next').onclick=()=>show(pos+1);q('feed').onclick=()=>{document.body.classList.add('feed');q('feed').setAttribute('aria-pressed','true');q('desktop').setAttribute('aria-pressed','false')};q('desktop').onclick=()=>{document.body.classList.remove('feed');q('feed').setAttribute('aria-pressed','false');q('desktop').setAttribute('aria-pressed','true')};show(0);</script></html>'''
(OUT/'index.html').write_text(viewer,encoding='utf-8')
r=load(BASE+'/reader-script.json');e=html.escape
reader=head+'<title>'+e(r['title'])+'</title>'+style+'<main><a href="index.html">'+e(r['return_label'])+'</a><article><p>China · Chip-design case</p><h1>'+e(r['title'])+'</h1><p class="entity">'+e(r['entity'])+'</p><p>'+e(r['intro'])+'</p>'+''.join('<h2>'+e(s['title'])+'</h2><p>'+e(s['text'])+'</p>' for s in r['sections'])+'<div class="source"><p>'+e(r['source_language'])+'</p><a href="'+e(r['source_url'])+'">'+e(r['source_cta'])+'</a></div></article><a href="index.html">'+e(r['return_label'])+'</a></main></html>'
(OUT/'case-reader.html').write_text(reader,encoding='utf-8')
# Compact actual-artwork audit page; no resampling of PNG bytes.
compact=head+'<title>B13 actual8 artwork review</title>'+style+'<main><h1>B13 · Actual8 artwork</h1><p>Feed333px · review includes CHANGES_REQUIRED case1.</p>'+''.join('<article id="'+e(c['card_id'])+'"><h2>'+e(c['card_id'])+'</h2><p>'+e(c['caption'])+'</p><img style="display:block;width:333px;max-width:100%;height:auto" src="'+e(c['image'])+'" alt="'+e(c['alt'])+'"><p>'+e(c['native_headline'])+'</p></article>' for c in cards if c['image'])+'</main></html>'
(OUT/'compact-review.html').write_text(compact,encoding='utf-8')
put(OUT.relative_to(ROOT).as_posix()+'/manifest.json',dict(revision='b13-review-manifest-v1',status='HOLD_CHANGES_REQUIRED',imagegen_original=8,imagegen_corrective=2,reused_pngs=0,generated_selected=8,planned_units=10,not_generated=['RMK-BRIGHT-3','RMK-BRIGHT-4'],tool='built-in image_gen',artwork=pins,viewer_sha256=hashlib.sha256((OUT/'index.html').read_bytes()).hexdigest(),reader_sha256=hashlib.sha256((OUT/'case-reader.html').read_bytes()).hexdigest(),raster_transformation=False,zip=False))
(OUT/'README.md').write_text('# B13 English Fabless F1 · partial review folder\n\nHOLD / CHANGES_REQUIRED. Eight of ten artwork units generated,8original +2corrective built-in ImageGen calls; no reuse. RMK-BRIGHT-1 source text is smaller than body and would require corrective3, beyond cap. RMK-BRIGHT-3/4 not generated. No approval or complete-set claim.\n\nOpen index.html for the ten-position journey, case-reader.html for the English source summary and compact-review.html for actual8artwork. Missing artwork is explicitly labelled, not fabricated. Native1254square PNG bytes copied unchanged. Prompt set selected-prompts.json. Full gate/attempt/evidence files in the owned operations folder. Stop before B14; no commit/merge/push/live.\n',encoding='utf-8')
print('B13 folder:8actual PNGs,10-position script viewer,reader,compact audit,manifest/prompts. HOLD.')
