"""Reviewed v5 six-card explanation, new immutable releases, frozen core untouched."""
import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).parent.parent/'B13-en-f1-v1'))
from prepare_draft import *
OLD=BASE;BASE=Path(__file__).parent.relative_to(ROOT).as_posix()
V4='deliverables/linkedin-safe-batches/parallel-fabless-2026-10-07/B13-en-f1-v4'
core=module('scripts/verify_imagegen_preflight.py');guard=module('scripts/verify_imagegen_anchor_preflight.py')
assert not (ROOT/BASE/'dispatch-plan.json').exists()
po=dict(revision='b13-v5-po-mandate-v1',instruction='Visual ổn r, content phần explanation thêm cho Bảo cần 1 card nuance về đội ngũ tư vấn, triển khai ở VN. Chạy lại v5.',accepted_visual=dict(path=V4+'/manifest.json',sha256=sha(V4+'/manifest.json'),scope='Visual v4 accepted by PO; technical evidence findings not upgraded'),scope='Offline B13 v5, six explanation images with consistent1/6..6/6, reuse cold+four proof PNGs byte-identical;11units+reader,6basecalls and max2corrective/1percard; stop before B14; no commit/merge/push',owner='/root current Fabless session')
put(BASE+'/generation-mandate.json',po)
src=dict(revision='b13-v5-vietnam-team-source-v1',observed_date='2026-10-07',sources=[dict(url='https://www.digiwin.com.vn/casestudies/huakun-electronic-viet-nam-san-xuat-thong-minh-digiwin-erp/',locator='136,143,162-167,184',observation='Official Digiwin Vietnam publication describes electronics manufacturer in Vietnam, Workflow ERP implementation, consulting/training team and coordination. Local service presence only; no metrics/customer testimonial reused.'),dict(url='https://www.digiwin.com.vn/about-vn/',locator='Company introduction and solution ecosystem',observation='ERP/digital provider role. Group headcounts excluded; not Vietnam headcounts.')],allowed='Consulting and implementation team in Vietnam; prospective discussion of reporting workflows/update ownership/project priorities',excluded=['Vietnam Fabless customer implementation','semiconductor-specific local team certification','all outcome metrics/headcounts/time guarantees','multilingual capability promise across all teams','new customer testimonial or mark'],proof_bridge='Local service context separate from China Bright case. Team card invites discussion; China case remains original qualitative outsourcing-management proof.')
put(BASE+'/vietnam-team-source.json',src)
cp=load(OLD+'/explanation/public-copy.json');cp['revision']='b13-explanation-en-copy-v5';ad=cp['ads'][0]
for i,c in enumerate(ad['cards'],1):c['artwork_labels'][-1]=str(i)+'/6'
ad['cards'].append(card('F1-A6','Consulting and implementation in Vietnam','Work with our team in Vietnam on ERP consulting and implementation. Start with your reporting workflows, update ownership and project priorities.','Digiwin Vietnam · ERP consulting and implementation',labels=['ERP · CHIP OPERATIONS','6/6']))
put(BASE+'/explanation-copy.json',cp)
put(BASE+'/reader-script.json',load(OLD+'/reader-script.json'))
(ROOT/BASE/'execution-brief.md').write_text('''# B13 v5 reviewed execution brief

Same FDI English Operations/SCM decision unit, commercial Fabless with outsourced production. Cold -> six explanation cards (lot reference, stage/time/source, owner, shared basis, Vietnam consulting/implementation discussion) -> qualitative named China outsourcing-management integrated-solution case -> English reader. Local-team service presence is separately source-backed; China case is not a Vietnam deployment or proof of exact F1 mechanism. No ROI/headcount/metric/capability expansion. Final11units:6fresh explanation,5cold/proof reuse byte-identical. All fields, scenes, source and ten transitions rechecked by root SELF_REVIEW; no independent/native-market certification. User visually accepted v4, no retrospective technical PASS. Frozen24/core/adapter unchanged; no Git/live/B14.
''',encoding='utf-8')
semantic=load(OLD+'/semantic-review.json');semantic.update(revision='b13-v5-actual-script-review-v1',stage='PREGEN_SCRIPT',verdict='SCRIPT_REVIEW_PASS',anchor_verdict='MESSAGE_ANCHOR_PASS',review_method='Actual root reread anchor/email, all new6fields, unchanged cold/proof/reader, new Vietnam-source publication, six storyboards and ten journey edges. Receipt authored after semantic comparison, no automatic approval.',A7='Same Operations/SCM: shared report basis -> local Vietnam consulting/implementation discussion -> named China chip-design case. Prospect discussions of reporting/update responsibilities are separate from published customer implementation. Reader remains original China source summary; no fabricated Vietnam Fabless deployment or ERP-only causality.',brand_role='Official logo once on every artwork. NewA6 publisher source is Digiwin Vietnam for provenance, not redundant brand header; existing source roles retained. No duplicated extra DIGIWIN label.',advertiser_voice='NewA6 Work with our team in Vietnam, direct supplier invitation. Existing We provide caption/direct questions retained; China customer stays third person. No third-person supplier praise.',reader='Reader unchanged exact content and original Chinese-language source disclosure; Vietnam-team source recorded separately, no claim Bright was served by Vietnam team.',per_unit_disposition={**semantic['per_unit_disposition'],'F1-A6':'MATCH: local consulting/implementation availability and concrete first-discussion workflow/owner/project priorities. No outcome or local Fabless deployment claim.'})
semantic.pop('draft_manifest_sha256',None);semantic['findings_closed']=['A1-A5 only sequence denominator5->6, exact headline/body/source/CTA unchanged','A6 Vietnam service presence supported by official local electronics ERP project publication, no numbers/testimonial borrowed','Whole11unit journey checked; local service statement not confused with China customer case','V4 visual PO adoption recorded separately; all changed6 must undergo postgen native/render review']
put(BASE+'/semantic-review.json',semantic)
v4assets={x['card_id']:x for x in load(V4+'/manifest.json')['artwork']}
oldcalls={}
for fp in [OLD+'/explanation/release-v3/campaign/spec.json',OLD+'/explanation/release-v2/closing/spec.json']:
 for call in load(fp)['calls']:oldcalls[call['targets'][0]]=call
observations=[]
for c in ad['cards']:
 if c['card_id']!='F1-A6':
  scene=oldcalls[c['card_id']]['concepts'][0]['description'];obs='Only sequence denominator changed to6; exact rest of copy and approved visual meaning retained. '+semantic['per_unit_disposition'][c['card_id']]
 else:
  scene='Bright illustrative consultation tabletop with two distinct blank project folios, a neutral chip sample and open blue physical paths between unlabelled responsibility tokens. Generic discussion material, not a customer facility, staff portrait or software UI. Compact scene leaves a large full-width plain white source block, source at least body-sized. No map/flag/skyline/ticks/labels/data/results or fabricated people.';obs=semantic['per_unit_disposition']['F1-A6']
 observations.append(dict(card_id=c['card_id'],observation=obs,scene=scene,source_scope=c['source_text']))
put(BASE+'/storyboard-review.json',dict(revision='b13-v5-storyboard-v1',cards=observations))
ids=[c['card_id'] for c in ad['cards']];fields={ad['ad_id']:['caption']+[c['card_id']+'.'+f for c in ad['cards'] for f in core.CARD_FIELDS]}
plans=[]
for i,cx in enumerate(ad['cards']):
 cid=cx['card_id'];folder=BASE+'/release/'+cid.lower();c=load(OLD+'/explanation/release-v3/campaign/contract.json');c.update(revision='b13-v5-'+cid+'-contract',copy=ref(BASE+'/explanation-copy.json'),card_order={ad['ad_id']:ids},groups=[[cid]])
 c['groups']=[[x] for x in ids]
 c['sources']=[x for x in c['sources'] if not x['path'].startswith(OLD)]+[ref(BASE+'/execution-brief.md','b13-v5-brief'),ref(BASE+'/vietnam-team-source.json'),ref(BASE+'/semantic-review.json')]
 c['card_sources']={x['card_id']:[s['path'] for s in c['sources']] for x in ad['cards']}
 c['surfaces']={ad['ad_id']:[dict(surface_id='full-feed',reading_order=['caption']+[x['card_id']+'.'+f for x in ad['cards'] for f in core.CARD_FIELDS])]}
 brand=next(r for r in c['references'] if r['role']=='brand_asset');style=next(r for r in c['references'] if r['role']=='campaign_visual')
 if cid!='F1-A6':
  art=v4assets[cid];target=dict(style,path=art['path'],sha256=sha(art['path']),revision='b13-v4-po-visual-accepted-edit-target')
  c['references']=[target,brand];c['style']['campaign']['instructions']+=' TARGETED EDIT OF FIRST IMAGE: preserve all exact existing headline/body/source/CTA/logo and photographic scene. Change ONLY printed sequence '+str(i+1)+'/5 to '+str(i+1)+'/6. Do not remove existing props or source, do not restyle. First reference is edit target, not customer proof.'
 else:
  target=dict(style,path=v4assets['F1-A5']['path'],sha256=sha(v4assets['F1-A5']['path']),revision='b13-v4-po-visual-accepted-style-only');c['references']=[target,brand]
 c['output']['directory']=folder+'/native';put(folder+'/contract.json',c);cr=ref(folder+'/contract.json');pr=c['copy']
 review=dict(schema_version=1,revision='b13-v5-'+cid+'-review',writer='/root',reviewer='/root',date='2026-10-07',scope='OFFLINE_SOURCE_COPY',independence='SELF_REVIEW',subjects=dict(contract=cr,copy=pr,sources=c['sources']),verdicts=dict(source_copy='PASS',editorial='PASS',first_mention='PASS'),reviewed_ads=c['ad_order'],reviewed_fields=[a+'/'+f for a,fs in fields.items() for f in fs],unresolved_findings=[]);put(folder+'/review.json',review)
 rel=dict(schema_version=1,revision='b13-v5-'+cid+'-release',authorizer='/root recording PO v5 mandate',authority_ref=ref(BASE+'/generation-mandate.json'),purpose='OFFLINE_IMAGEGEN',contract=cr,copy=pr,review=ref(folder+'/review.json'),groups=[[cid]]);put(folder+'/release.json',rel)
 call=copy.deepcopy(oldcalls[cid] if cid!='F1-A6' else oldcalls['F1-A5']);call.update(call_id='B13_V5_'+cid.replace('-','_'),targets=[cid],output_id=cid.lower()+'-b13-en-v5',output_path=folder+'/native/'+cid.lower()+'-b13-en-v5.png',references=c['references'],artwork_text={cid:{f:cx[f] for f in ['headline','body','source_text','cta','artwork_labels']}})
 o=observations[i];call['concepts']=[dict(card_id=cid,concept_id='b13-v5-'+cid+'-scene',description=o['scene'],props=['blank project folios','neutral chip sample'] if cid=='F1-A6' else oldcalls[cid]['concepts'][0]['props'],reader_question=cx['headline'],artwork_labels=cx['artwork_labels'])]
 call['prompt']=core.make_prompt(c,call);call['prompt_sha256']=hashlib.sha256(call['prompt'].encode()).hexdigest();put(folder+'/spec.json',dict(schema_version=1,revision='b13-v5-'+cid+'-spec',release=ref(folder+'/release.json'),contract=cr,copy=pr,review=rel['review'],calls=[call]))
 script=dict(revision='b13-v5-'+cid+'-script',gate_id='AD-ED-01',stage='PREGEN_SCRIPT',verdict='SCRIPT_REVIEW_PASS',copy_sha256=pr['sha256'],reviewed_ads=c['ad_order'],reviewed_fields=fields,BRAND_ROLE=dict(verdict='PASS',observation=semantic['brand_role']),ADVERTISER_VOICE=dict(verdict='PASS',observation=semantic['advertiser_voice']),independence='SELF_REVIEW',per_card_observations=observations,reader_script=ref(BASE+'/reader-script.json'),actual_review_ref=ref(BASE+'/semantic-review.json'),postgen='POSTGEN_NOT_RUN');put(folder+'/script-review.json',script)
 anchor=load(OLD+'/explanation/release-v3/campaign/anchor-review.json');anchor.update(revision='b13-v5-'+cid+'-anchor',subjects=dict(contract=cr,copy=pr,spec=ref(folder+'/spec.json'),script_review=ref(folder+'/script-review.json')),coverage=dict(ads=c['ad_order'],cards=ids,fields=fields,storyboard_cards=ids),units=[dict(card_id=o['card_id'],verdict='MATCH',observation=o['observation']+' Scene: '+o['scene']) for o in observations],transitions=[dict(cards=[a['card_id'],b['card_id']],verdict='MATCH',observation=a['headline']+' -> '+b['headline']+'; same Operations/SCM reporting business question, local service discussion and China case separately attributed') for a,b in zip(ad['cards'],ad['cards'][1:])])
 anchor['rules']={k:dict(verdict='N/A' if k=='A5' else 'MATCH',observation=semantic[k]) for k in ['A1','A2','A3','A4','A5','A6','A7']}
 anchor['context']=dict(scope='FULL_JOURNEY',verdict='MATCH',observation=semantic['A7']+' Reader: '+semantic['reader'],brief=ref(BASE+'/execution-brief.md','b13-v5-brief'),related_inputs=[ref(OLD+'/cold/public-copy.json'),ref(OLD+'/proof/public-copy.json'),ref(BASE+'/reader-script.json'),ref(BASE+'/semantic-review.json'),ref(BASE+'/vietnam-team-source.json'),ref(OLD+'/proof-source-mapping.json')]);put(folder+'/anchor-review.json',anchor)
 checked=guard.check(ROOT,folder+'/release.json',sha(folder+'/release.json'),folder+'/spec.json',folder+'/anchor-review.json',sha(folder+'/anchor-review.json'),call['call_id'],'FDI',PERSONA,ROUTE);put(folder+'/preparation-preflight.json',checked)
 plans.append(dict(folder=folder,call_id=call['call_id'],card_id=cid,output_path=call['output_path'],release_sha256=sha(folder+'/release.json'),review_sha256=sha(folder+'/anchor-review.json')))
plans.sort(key=lambda x:['F1-A6','F1-A5','F1-A1','F1-A2','F1-A3','F1-A4'].index(x['card_id']))
put(BASE+'/dispatch-plan.json',dict(revision='b13-v5-dispatch',persona=PERSONA,route=ROUTE,calls=plans,fresh_preflight_required=True))
shutil=__import__('shutil');shutil.copyfile(ROOT/OLD/'fresh_preflight.py',ROOT/BASE/'fresh_preflight.py');shutil.copyfile(ROOT/OLD/'record_attempt.py',ROOT/BASE/'record_attempt.py');shutil.copyfile(ROOT/OLD/'prepare_draft.py',ROOT/BASE/'prepare_draft.py')
print('V5 six reviewed calls prepared: canaryA6,A5; original bindings untouched.')
