"""Owned offline IC700/Aplus input assembly. Reviewer observations are root self-review."""
from pathlib import Path
import json, hashlib, importlib.util, copy
ROOT=Path(__file__).resolve().parents[3]
B='operations/linkedin-vn-journey-rebuild/2026-10-06/journey-v3'
P=ROOT/B; P.mkdir(exist_ok=True)
OLD=ROOT/'operations/linkedin-vn-journey-rebuild/2026-10-06/journey-v1'
def read(path):return json.loads(path.read_text(encoding='utf-8-sig'))
def write(name,value):(P/name).write_bytes((json.dumps(value,ensure_ascii=False,indent=2)+'\n').encode('utf-8'))
def sha(path):return hashlib.sha256((ROOT/path).read_bytes()).hexdigest()
def ref(name,rev):return {'path':B+'/'+name,'sha256':sha(B+'/'+name),'revision':rev}
def ext(path,rev):return {'path':path,'sha256':sha(path),'revision':rev}
def module(path,name):
 s=importlib.util.spec_from_file_location(name,ROOT/path);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
core=module('scripts/verify_imagegen_preflight.py','core')
caption='Với kinh nghiệm tư vấn hơn 700 khách hàng IC trong ngành bán dẫn, chúng tôi đồng hành cùng Quý Doanh Nghiệp chuẩn bị năng lực quản trị để đáp ứng yêu cầu đánh giá của khách hàng.'
rows=[
 ('VN-R1','700+\nkhách hàng IC','Kinh nghiệm tư vấn trong ngành bán dẫn.\nChúng tôi đồng hành cùng doanh nghiệp Việt.','Kinh nghiệm tư vấn hơn 700 khách hàng IC','', 'A sculptural large blue typographic700+ above an open consulting folder and small generic electronic component; count clearly belongs to headline not diagram records. No maps, locations, badges or client marks.', ['consulting folder','generic electronic component']),
 ('VN-R2','Khách hàng yêu cầu audit.\nHồ sơ đã sẵn sàng?','Cùng chúng tôi chuẩn bị năng lực quản trị\nđể đáp ứng yêu cầu đánh giá của khách hàng.','Chuẩn bị hồ sơ cho đánh giá khách hàng','', 'A neat review desk with a blank request sheet standing opposite an open blue process binder; a clear review gap invites preparation, no pass stamp or certificate.', ['request sheet','process binder']),
 ('VN-R3','Mỗi sản phẩm\ncần một lịch sử rõ ràng.','Tại Aplus, iMES lưu lịch sử từng sản phẩm\nđể đội ngũ tra lại dữ liệu.','Aplus: truy xuất lịch sử từng sản phẩm','', 'One generic flexible-film electronic component on a tray connected to a sequence of three tactile blank history tiles with barcode-like abstract marks. No printed numbers or software screens.', ['flexible-film component','history tiles','tray']),
 ('VN-R4','Thay đổi tham số.\nĐội ngũ kiểm soát thế nào?','Tại Aplus, hệ thống quản lý tham số kỹ thuật\nvà hỗ trợ kiểm soát chất lượng bằng SPC.','Aplus: kiểm soát tham số và chất lượng','', 'Two distinct blank parameter plates sliding into an engineering review slot beside a quality measurement block; controlled change, no charts/numbers or invented interface.', ['parameter plates','review slot','measurement block']),
 ('VN-R5','Quý Doanh Nghiệp\ncần chuẩn bị từ đâu?','Xem case Aplus Semiconductor tại Trung Quốc:\ntriển khai iMES + TOP GP trước audit khách hàng.','Xem case Aplus Semiconductor','Xem case Aplus', 'An open case dossier with one unbranded flexible-film electronic component and an orange reading tab; physical editorial document, not a fake outcome report.', ['case dossier','electronic component','reading tab']),
 ('VN-E1','Chuẩn bị hệ thống\ntrước audit khách hàng.','Aplus Semiconductor tại Trung Quốc\ntriển khai iMES + TOP GP.','Aplus: iMES + TOP GP tại Trung Quốc','', 'A bright editorial still life of generic COF-style flexible-film components and two aligned system blocks at a preparation desk; no real plant or customer logo.', ['COF-style components','two system blocks','preparation desk']),
 ('VN-E2','Tra lại lịch sử\ntừng sản phẩm.','Tại Aplus, báo công theo serial\nhỗ trợ truy xuất lịch sử từng sản phẩm.','Aplus: lịch sử theo từng serial','', 'A single flexible-film component on an individual tray aligned with an upright barcode-like blank ticket and an unfolding record strip; individual product history, no words on props.', ['individual tray','blank ticket','unfolding record strip']),
 ('VN-E3','Dữ liệu kiểm tra\nđược phân tích bằng SPC.','Tại Aplus, hệ thống ghi nhận dữ liệu\nvà cảnh báo chất lượng theo thời gian thực.','Aplus: dữ liệu kiểm tra và cảnh báo','', 'A clean tabletop optical measurement fixture with generic film sample, a translucent data panel and one restrained amber alert marker; no actual chart, numbers or false software interface.', ['measurement fixture','film sample','translucent data panel','alert marker']),
 ('VN-E4','Quý Doanh Nghiệp\nđã chuẩn bị đến đâu?','Cùng chúng tôi trao đổi nhu cầu quản trị,\ntừ quy trình và dữ liệu hiện có.','Trao đổi nhu cầu chuẩn bị quản trị','Trao đổi nhu cầu', 'An inviting open preparation workbook, a precision industrial component and two blank dialogue cards resting on a bright tabletop; no audit badge, certificate or approval cue.', ['preparation workbook','precision component','dialogue cards'])]
ads=[]
for aid,indices,cap,label in [('VN-RMK-READINESS',range(5),caption,'BÁN DẪN · CHUẨN BỊ NĂNG LỰC QUẢN TRỊ'),('VN-EVIDENCE-APLUS',range(5,9),'Để chuẩn bị đáp ứng yêu cầu đánh giá của khách hàng, Quý Doanh Nghiệp cần những hồ sơ nào? Cùng chúng tôi xem case Aplus Semiconductor tại Trung Quốc, do DigiHua công bố, với giải pháp iMES + TOP GP.','CASE BÁN DẪN · TRUNG QUỐC')]:
 cards=[]
 for i in indices:
  cid,h,body,native,cta,scene,props=rows[i]
  cards.append({'card_id':cid,'headline':h,'body':body,'source_text':'Nguồn: Digiwin' if i==0 else '' if i==1 or i==8 else 'Nguồn case: DigiHua','cta':cta,'native_headline':native,'alt':'Digiwin: '+h.replace('\n',' ')+' '+body.replace('\n',' '),'artwork_labels':[label]})
 ads.append({'ad_id':aid,'caption':cap,'cards':cards})
pub={'schema_version':1,'revision':'VN-journey-v3-IC700-Aplus-copy','ads':ads};write('public-copy.json',pub)
(P/'authority.md').write_bytes(('Bảo: okie commit checkpoint và cách áp dụng nuance ở trên vừa chốt, r chạy gent lại. Checkpoint6345f7d local. Root owner, no agents. Offline9base +at most1targeted correction/card; Cold exact frozen. IC700 consulting experience without geography or audit success count. Aplus China iMES+TOP GP, DigiHua source; no claim Vietnamese team executed case, ERP-only causality, certification/order guarantee. Demo internal, no live/publish/spend.\n').encode('utf-8'))
sources=ext('operations/linkedin-vn-journey-rebuild/2026-10-06/IC700_Claim_Scope.json','PO-nuance-700')
case={'revision':'Aplus-bounded-source-20261006','url':'https://www.digihua.com/常州欣盛半导体技术股份有限公司/','method':'web open actual page text, checked2026-10-06','entity':'常州欣盛半导体技术股份有限公司 / Aplus Semiconductor Technologies','market':'China','scope':'COF semiconductor case; audit demand motivated iMES+TOP GP deployment. Individual serial history, SPC recording/alerts and engineering parameter management disclosed.','excluded':['successful audit verdict','ERP-only attribution','guaranteed timeline','VN deployment outcome','customer logo or real facility reuse']};write('case-source.json',case)
c=read(OLD/'contract.json');c['revision']='VN-journey-v3-contract';c['copy']=ref('public-copy.json',pub['revision']);c['sources']=[ref('authority.md','Bao-regeneration-mandate'),sources,ref('case-source.json',case['revision'])]
c['ad_order']=[a['ad_id'] for a in ads];c['card_order']={a['ad_id']:[x['card_id'] for x in a['cards']] for a in ads}
c['card_sources']={row[0]:[s['path'] for s in c['sources']] for row in rows}
c['surfaces']={}
fields={};flat=[]
for ad in ads:
 aid=ad['ad_id'];fields[aid]=['caption']+[x['card_id']+'.'+field for x in ad['cards'] for field in core.CARD_FIELDS];flat.extend(aid+'/'+x for x in fields[aid]);c['surfaces'][aid]=[{'surface_id':'feed','reading_order':fields[aid]},{'surface_id':'raster','reading_order':[x['card_id']+'.'+field for x in ad['cards'] for field in core.ART_FIELDS]}]
c['style']['avoid'][-1]='Numerical claims beyond exactly approved700 consulting-experience wording; audit success or certification guarantees'
c['style']['campaign']={'revision':'VN-journey-v3','instructions':'One square ad. Same bright white, pale blue, navy and tactile campaign family. Official logo once upper left. Approved category compact but legible; no page number. Main headline very large, bold, readable at332px; body minimum50px equivalent on1254 square. Headline/body/labels/source/CTA only exact approved wording; no additional diagram labels.700+ is very large on R1, qualified by exact consulting-experience body; no maps or geographical claim. Source footer visibly readable. No faces, customer logos, certifications, fake UI, unapproved numbers, false guarantee. Scenes editorial illustrations, not actual facilities. Film components only where case-relevant. Distinct scene per card. Direct address exact Quý Doanh Nghiệp. Do not print captions, alt or native headlines.'}
c['output']['directory']=B+'/native';write('contract.json',c)
review={'schema_version':1,'revision':'VN-journey-v3-mechanical-review','writer':'/root','reviewer':'/root','date':'2026-10-06','scope':'OFFLINE_SOURCE_COPY','independence':'SELF_REVIEW','subjects':{'contract':ref('contract.json',c['revision']),'copy':c['copy'],'sources':c['sources']},'verdicts':{'source_copy':'PASS','editorial':'PASS','first_mention':'PASS'},'reviewed_ads':c['ad_order'],'reviewed_fields':flat,'unresolved_findings':[]};write('review.json',review)
release={'schema_version':1,'revision':'VN-journey-v3-release','authorizer':'/root recording explicit Bao offline generation mandate','authority_ref':ref('authority.md','Bao-regeneration-mandate'),'purpose':'OFFLINE_IMAGEGEN','contract':ref('contract.json',c['revision']),'copy':c['copy'],'review':ref('review.json',review['revision']),'groups':c['groups']};write('release.json',release)
spec={'schema_version':1,'revision':'VN-journey-v3-spec','release':ref('release.json',release['revision']),'contract':release['contract'],'copy':release['copy'],'review':release['review'],'calls':[]}
for row in rows:
 cid,h,body,native,cta,scene,props=row;card=next(x for a in ads for x in a['cards'] if x['card_id']==cid);oid=cid.lower()+'-v3'
 call={'call_id':cid+'-V3','targets':[cid],'references':c['references'],'concepts':[{'card_id':cid,'concept_id':cid+'-IC700-Aplus-v3','reader_question':h.replace('\n',' '),'description':scene,'props':props,'artwork_labels':card['artwork_labels']}],'artwork_text':{cid:core.artwork(card)},'output_id':oid,'output_path':B+'/native/'+oid+'.png'}
 call['prompt']=core.make_prompt(c,call);call['prompt_sha256']=hashlib.sha256(call['prompt'].encode()).hexdigest();spec['calls'].append(call)
write('spec.json',spec)
obs={
'VN-R1':'700+ qualified immediately as consulting experience/IC, no geography, no audit count; speaker chúng tôi, domestic-reader preparation; source publisher count.',
'VN-R2':'Customer audit trigger and complete readiness question; subject hồ sơ, advertiser invitation. No audit-success promise; management preparation relevance.',
'VN-R3':'Aplus named as case example, iMES owns individual-product history; explains checkable record mechanism, no ERP-only claim.',
'VN-R4':'Aplus engineering parameters and SPC named; subject hệ thống, concrete change/quality process and source; not generic specialist slogan.',
'VN-R5':'Quý Doanh Nghiệp exact direct address; named China case iMES+TOP GP before audit, not passed audit; case reading next step.',
'VN-E1':'Aplus China semiconductor identity and product named, audit preparation motive only. DigiHua source footer; no attributed customer quotation.',
'VN-E2':'Serial-based reporting and per-product history attributed to Aplus; checkable preparation mechanism, not universal outcome.',
'VN-E3':'SPC statistics and real-time quality alert explicitly named and case-attributed; no measured defect/yield reduction or ERP claim.',
'VN-E4':'Quý Doanh Nghiệp invitation from chúng tôi to discuss existing records/process. No promised consulting package, free assessment or certification.'}
scope={'segment':'VN_DOMESTIC','locale':'vi-VN','persona':'domestic supplier owner / operations director','route':'Cold-v4 to IC700 preparation RMK to Aplus semiconductor evidence'}
scanner=module('operations/linkedin-vn-journey-rebuild/2026-10-06/reader-address/verify_vn_reader_address.py','address');scan=scanner.scan(dict(scanner.copy_fields(pub)),'PREGEN_SCRIPT');assert not scan['findings'];write('address-scan.json',scan)
v={'gate_id':'VN-VOICE-01','revision':'VN-journey-v3-voice-pregen','stage':'PREGEN_SCRIPT','date':'2026-10-06','writer':'/root','reviewer':'/root','independence':'SELF_REVIEW','verdict':'VN_VOICE_PASS','policy':ext('operations/VN_Locale_Reader_Voice_Gate.md','1.1'),'freeze':ext('operations/linkedin-vn-journey-rebuild/2026-10-06/VN_Cold_Nuance_Freeze_2026-10-06.json','Cold-v4-frozen'),'copy':c['copy'],'spec':ref('spec.json',spec['revision']),'scope':scope,'reviewed_fields':fields,'units':[{'card_id':x['card_id'],'exact_fields':x,'V1_V4_observation':obs[x['card_id']],'V5_observation':'Exact direct-reader Quý Doanh Nghiệp in R5/E4; other units descriptive/case subjects, not personal address. Every field reviewed; empty fields N/A by design.','verdict':'VN_VOICE_PASS'} for a in ads for x in a['cards']],'captions':[{'ad_id':a['ad_id'],'exact_text':a['caption'],'observation':'Speaker chúng tôi and exact Quý Doanh Nghiệp; independent preparation context, publisher/case attributed, no outcome guarantee.'} for a in ads],'reader_address':{'verdict':'PASS','scan':ref('address-scan.json','V5-pregen-v3'),'dispositions':{locator:'PASS: exact formal address or descriptive/case wording; empty field N/A' for locator in dict(scanner.copy_fields(pub))}},'postgen':'POSTGEN_NOT_RUN','unresolved_findings':[]};write('vn-voice-pregen.json',v)
script={'gate_id':'AD-ED-01','stage':'PREGEN_SCRIPT','revision':'VN-v3-editorial-script','copy_sha256':c['copy']['sha256'],'writer':'/root','reviewer':'/root','independence':'SELF_REVIEW','verdict':'SCRIPT_REVIEW_PASS','reviewed_ads':c['ad_order'],'reviewed_fields':fields,'BRAND_ROLE':{'verdict':'PASS','observation':'Official logo only, consulting/case source attributed; not customer-owned ad.'},'ADVERTISER_VOICE':{'verdict':'PASS','observation':'Each caption chúng tôi; technical sentences case-attributed not third-party Digiwin narration.'},'VN_VOICE':{'verdict':'PASS','receipt':ref('vn-voice-pregen.json',v['revision'])},'unit_observations':obs,'unresolved_findings':[],'postgen':'POSTGEN_NOT_RUN'};write('script-review-detail.json',script)
anchor={'schema_version':1,'revision':'VN-v3-anchor-review','gate_id':'MSG-ANCHOR-01','stage':'PREGEN_SCRIPT','verdict':'MESSAGE_ANCHOR_PASS','anchor':ext('operations/Vy_Email_Content_Anchor.md','1.0'),'source':ext('operations/source-evidence/Vy_Email_User_Provided_2026-10-06.md','VY-MAIL-USER-20261006'),'subjects':{'contract':release['contract'],'copy':release['copy'],'spec':ref('spec.json',spec['revision']),'script_review':ref('script-review-detail.json',script['revision'])},'scope':scope,'writer':'/root','reviewer':'/root','independence':'SELF_REVIEW','coverage':{'ads':c['ad_order'],'cards':[x[0] for x in rows],'fields':fields,'storyboard_cards':[x[0] for x in rows]},'rules':{k:{'verdict':'MATCH','observation':o} for k,o in {'A1':'Domestic supplier operations/owner readiness, not corporate fab buyer.','A2':'Specific influencing/decision role tied to records/process preparation; no live ICP claim.','A3':'Vietnamese domestic journey distinct from FDI ROI; China case geography does not change reader.','A4':'Business value checkable records/controls for assessment preparation; no financial ROI invented.','A5':'Readiness invitation, no qualification or guaranteed audit approval.','A6':'Industry depth individual history, SPC and engineering parameters with correct solution attribution.','A7':'Cold invitation to consulting-experience trigger then mechanisms then named semiconductor case and need discussion.'}.items()},'units':[{'card_id':x[0],'verdict':'MATCH','observation':obs[x[0]]} for x in rows],'transitions':[{'cards':[a['card_id'],z['card_id']],'verdict':'MATCH','observation':obs[a['card_id']]+' Next: '+obs[z['card_id']]} for ad in ads for a,z in zip(ad['cards'],ad['cards'][1:])],'context':{'scope':'FULL_JOURNEY','verdict':'MATCH','observation':'Frozen Cold200 selection count not same population as700 IC consulting experience. Preparation promise persists. RMK case mechanisms iMES not ERP substitute, Aplus China attributed; final direct Vietnamese discussion route. Public Chinese case is optional source reading, not VN localized landing deployment.','brief':ext('operations/linkedin-vn-journey-rebuild/2026-10-06/IC700_Nuance_Application.md','PO-approved-nuance-application'),'related_inputs':[ext('operations/linkedin-vn-journey-rebuild/2026-10-06/cold-v4/public-copy.json','Cold-v4-frozen')]},'unresolved_findings':[]};write('message-review.json',anchor)
pins={r['path']:r['sha256'] for r in [release['authority_ref'],release['contract'],release['copy'],release['review'],ref('release.json',release['revision']),ref('spec.json',spec['revision']),ref('message-review.json',anchor['revision']),ref('script-review-detail.json',script['revision']),ref('vn-voice-pregen.json',v['revision']),v['policy'],v['freeze'],ext('operations/linkedin-vn-journey-rebuild/2026-10-06/reader-address/verify_vn_reader_address.py','V5-checker')]};write('dispatch-pins.json',pins)
helper=(OLD/'dispatch-verify.py').read_text(encoding='utf-8-sig').replace('journey-v1','journey-v3');(P/'dispatch-verify.py').write_bytes(helper.encode())
guard=module(B+'/dispatch-verify.py','guard');results=[]
for call in spec['calls']:results.append({'call_id':call['call_id'],'status':guard.verify(call['call_id'])['status']})
write('preflight-all.json',results)
print(json.dumps({'status':'FRESH9_PREGEN_INPUTS_VERIFIED','calls':len(results),'address_scan':scan['scan_status']},ensure_ascii=True))
