"""Authored Traditional Chinese presentation copy. Source strings are exact VI nodes.
No machine-translation service; source artwork is not translated or regenerated.
"""
COPY = {
"Paid ads chuỗi cung ứng bán dẫn · Digiwin": "半導體供應鏈廣告提案 · Digiwin",
"Digiwin · Paid ads bán dẫn": "Digiwin · 半導體供應鏈廣告",
"Bắt đầu": "首頁",
"Đề xuất": "提案與預算",
"Logic quảng cáo": "廣告策略與假設",
"Demo": "內容示例",
"Thư viện": "素材庫",
"Đề xuất gửi Vy · 08/10/2026": "廣告投放提案 · 2026/10/08",
"Tiếp cận doanh nghiệp": "接觸半導體供應鏈中的",
"trong chuỗi cung ứng bán dẫn": "目標企業",
"Bảo đề xuất tập trung đúng tệp, mở bằng vấn đề quản trị và dẫn người quan tâm tới nội dung giải thích, case và giải pháp Digiwin.": "我建議先鎖定合適的企業與負責人，以管理問題引起關注，再透過進一步說明、案例與 Digiwin 解決方案，讓有興趣的人深入了解。",
"Vì sao chọn tệp này, nội dung này?": "為什麼選這些受眾、用這些內容？",
"Tệp chính và dự phòng, hai giả thuyết VN–FDI, hình ảnh minh họa và cách Bảo chọn hành động tuần 2 được trình bày trong một mạch.": "從主要與備用受眾名單、越南本土與外資企業的兩組假設，到視覺示例及第二週的調整方式，這裡說明整體思路。",
"Xem logic quảng cáo và hai ví dụ": "查看廣告策略與兩組示例",
"Trần đầu tư · chưa thuế": "投資上限 · 未稅",
"11,7 triệu": "1,170 萬越南盾",
"Cho toàn phương án LinkedIn và Search tùy chọn.": "涵蓋整體 LinkedIn 方案及可選的搜尋廣告。",
"Đợt LinkedIn đầu": "首輪 LinkedIn 投放",
"5,6 triệu": "560 萬越南盾",
"Một nhóm phù hợp, ít mẫu đại diện để tập trung ngân sách.": "先選一組合適的受眾與少量代表素材，集中預算觀察。",
"Giữ lại trong cùng trần": "同一總額內的保留預算",
"6,1 triệu": "610 萬越南盾",
"Chọn bước tiếp theo theo dữ liệu và mức chi thực tế.": "依數據與實際花費，決定下一步。",
"Xem logic quảng cáo": "查看廣告策略",
"Xem phương án và ngân sách": "查看方案與預算",
"3 điểm Vy xem giúp Bảo": "請你協助確認三點",
"Hai nhóm, hai hướng nội dung": "兩組受眾，兩種內容方向",
"Doanh nghiệp nội địa": "越南本土企業",
"Tiếng Việt mở bằng việc chuẩn bị năng lực quản trị, hồ sơ và dữ liệu để đáp ứng yêu cầu của khách hàng trong chuỗi bán dẫn.": "越南文內容從管理能力、文件與數據準備切入，協助企業因應半導體供應鏈客戶的要求。",
"Doanh nghiệp FDI": "外資企業（FDI）",
"English/Chinese mở từ vấn đề vận hành, rồi nối tới giá trị về thời gian, phối hợp, trách nhiệm và kiểm soát rủi ro.": "英文與中文內容從具體營運問題切入，再連結到時間、協作、責任分工與風險控管的價值。",
"Từ lần đầu thấy đến tìm hiểu sâu": "從初次接觸到深入了解",
"1. Ảnh đơn": "1. 單圖廣告",
"Đặt vấn đề với người đọc mới.": "向初次接觸的讀者提出一個明確問題。",
"2. Carousel": "2. 輪播廣告",
"Giải thích cho người đã tương tác với chính các quảng cáo mới, khi tệp đủ điều kiện.": "當與這批新廣告互動的受眾達到投放條件，再用輪播內容進一步說明。",
"3. Trang đọc case": "3. 案例閱讀頁",
"Làm rõ cơ chế và mở cuộc trao đổi về nhu cầu phù hợp.": "說明解決方式，並邀請有相關需求的人進一步交流。",
"Tuần 1 chạy đúng plan. Review cuối tuần để chọn hướng tuần 2 theo dữ liệu, trong trần ngân sách đề xuất.": "第一週按計畫執行，週末檢視數據，再於提議的預算上限內決定第二週的方向。",
"Xem cùng phương án": "搭配方案一起看",
"Demo nội dung": "內容示例",
"Xem luồng VN và FDI từ ảnh đơn tới case.": "查看本土與外資企業的內容流程：從單圖廣告到案例。",
"Mở demo": "查看內容示例",
"Thư viện để thay nội dung": "可供調整的素材庫",
"Hai luồng VN và các chủ đề OSAT bằng English, giản thể, phồn thể.": "包含兩組越南文流程，以及 OSAT 主題的英文、簡體中文與繁體中文素材。",
"Mở thư viện": "開啟素材庫",
"Theo dõi và review": "追蹤與檢視",
"Ngân sách, chi dashboard và dữ liệu theo từng kỳ.": "按觀察期間記錄預算、後台花費與成效數據。",
"Mở file theo dõi": "開啟追蹤表（越南文）",
"Xem nội dung mail": "查看郵件草稿",
"Bản đề xuất dạng văn bản": "文字版提案（越南文）",
"Ảnh bằng chứng": "查看佐證截圖",
"Bảo gửi Vy · 08/10/2026": "Digiwin · 廣告投放提案 · 2026/10/08",
"Đề xuất paid ads · Digiwin": "廣告投放提案 · Digiwin",
"Đề xuất paid ads cho chuỗi cung ứng bán dẫn": "半導體供應鏈廣告投放提案",
"Gửi:": "收件人：",
"Vy": "你",
"Phụ trách paid:": "投放負責人：",
"Bảo": "我",
"Ngày:": "日期：",
"08/10/2026": "2026/10/08",
"Bảo đề xuất ngân sách tối đa": "我建議將總預算上限定為",
"11,7 triệu đồng, chưa thuế": "11,700,000 越南盾（未稅）",
", để tiếp cận đúng doanh nghiệp trong chuỗi cung ứng bán dẫn và điện tử, tạo sự quan tâm đến bài toán quản trị và dẫn người đọc vào nội dung giải thích, case và giải pháp Digiwin. Vy xem giúp Bảo phương án và ba điểm ở cuối để tổng hợp, trình lãnh đạo.": "，接觸半導體與電子供應鏈中合適的企業，以管理議題引起興趣，再引導讀者了解相關說明、案例與 Digiwin 解決方案。請你協助看一下方案及最後的三點，方便彙整後向主管提報。",
"Tiếp cận ai, bằng thông điệp nào?": "接觸誰？傳達什麼訊息？",
"Tập trung vào doanh nghiệp làm PCB, substrate, linh kiện, vật liệu đóng gói và gia công chính xác cho thiết bị. Nội dung và tệp tiếp cận tách riêng theo hai nhóm.": "聚焦 PCB、載板、零組件、封裝材料，以及設備精密加工等企業。受眾與內容分為兩組，分別規劃。",
"Nội địa, tiếng Việt:": "本土企業，使用越南文：",
"ERP là bước chuẩn bị năng lực quản trị, hồ sơ, quy trình và dữ liệu để đáp ứng yêu cầu của khách hàng trong chuỗi cung ứng bán dẫn.": "以 ERP 作為建立管理能力、文件、流程與數據基礎的一環，協助企業準備因應半導體供應鏈客戶的要求。",
"FDI, English/Chinese:": "外資企業，使用英文或中文：",
"mở bằng vấn đề vận hành của người phụ trách, rồi làm rõ giá trị về thời gian, phối hợp, trách nhiệm và kiểm soát rủi ro. Bảo chọn ngôn ngữ theo nhóm người đọc.": "從負責人面對的營運問題切入，說明時間、協作、責任分工與風險控管的價值。我會依實際讀者選擇語言。",
"LinkedIn bắt đầu bằng ảnh đơn cho người đọc mới. Khi tệp người đã tương tác với chính các quảng cáo mới đủ điều kiện, carousel giúp giải thích sâu hơn. Trang đọc case nối vấn đề của người đọc với cơ chế giải pháp và lời mời trao đổi nhu cầu.": "LinkedIn 先以單圖廣告接觸新讀者。當與這批新廣告互動的受眾達到投放條件，再以輪播廣告深入說明。案例閱讀頁則連結讀者的問題與解決機制，邀請有相關需求的人交流。",
"Logic quảng cáo và cách điều chỉnh": "廣告策略與調整方式",
"Bảo chuẩn bị tệp chính từ 424 dòng công ty cung cấp và một tệp dự phòng gồm 52 Company Pages được nghiên cứu riêng. Cách tiếp cận đi từ đúng công ty tới phạm vi Việt Nam, chức năng công việc và cấp bậc phù hợp. Mapping và quy mô sau lọc là cơ sở để chọn tệp khi chạy.": "我以公司提供的 424 筆資料建立主要名單，另行研究並準備 52 個公司專頁作為備用名單。篩選順序是公司、越南地區、工作職能與適當職級；投放時依配對結果及篩選後的受眾規模選擇名單。",
"Giả thuyết VN nối yêu cầu của khách hàng trong chuỗi với năng lực quản trị cần chuẩn bị. Giả thuyết FDI mở từ tình huống vận hành, rồi làm rõ giá trị của dữ liệu và phối hợp. Hình ảnh, phần giải thích và case cùng giữ một bài toán để xây liên tưởng về Digiwin.": "本土企業的假設，是將供應鏈客戶的要求連結到需要準備的管理能力；外資企業的假設，則從營運情境說明數據與協作的價值。視覺、說明與案例圍繞同一個問題，建立讀者對 Digiwin 的聯想。",
"Review cuối tuần 1 giúp Bảo phân biệt vấn đề ở đo lường, tệp, phân phối hay nội dung. Tuần 2 thay đúng khâu cần cải thiện, giữ phần hiệu quả và chọn RMK khi tệp tương tác với chính quảng cáo mới đủ điều kiện.": "第一週末的檢視會區分問題出在衡量、受眾、廣告投遞還是內容。第二週針對需要改善的環節調整，保留有效部分；與這批新廣告互動的受眾達到條件後，再考慮再行銷。",
"Xem logic quảng cáo, hai ví dụ hình ảnh và matrix tuần 2": "查看廣告策略、兩組視覺示例與第二週決策表",
".": "。",
"Ngân sách chưa thuế": "預算（未稅）",
"Khoản": "項目",
"Mức đề xuất": "建議金額",
"Cách sử dụng": "使用方式",
"5.600.000 đồng": "5,600,000 越南盾",
"Chọn một nhóm phù hợp và ít mẫu đại diện để tập trung ngân sách, quan sát phân phối và mức quan tâm.": "選一組合適受眾與少量代表素材，集中預算，觀察投遞情況與關注程度。",
"LinkedIn tiếp theo": "後續 LinkedIn 投放",
"Tối đa 5.600.000 đồng": "最多 5,600,000 越南盾",
"Tiếp tục phần hiệu quả, thay đoạn cần cải thiện hoặc dùng remarketing khi tệp đủ điều kiện.": "延續有效部分、替換需要改善的環節，或於受眾符合條件時採用再行銷。",
"Search tùy chọn": "搜尋廣告（可選）",
"Tối đa 500.000 đồng": "最多 500,000 越南盾",
"Thử từ khóa thương mại phù hợp trong phạm vi nhỏ, chi theo lượng tìm kiếm thực tế.": "小規模測試合適的商業意圖關鍵字，按實際搜尋量花費。",
"Tổng": "合計",
"11.700.000 đồng": "11,700,000 越南盾",
"Trần ngân sách cho toàn phương án.": "整體方案的預算上限。",
"6,1 triệu đồng giữ lại nằm trong tổng 11,7 triệu": "保留的 610 萬越南盾已包含在總額 1,170 萬越南盾內",
", gồm LinkedIn tiếp theo và Search tùy chọn. Bảo quản lý, điều phối số tiền trên dashboard; kế toán xử lý thuế và thanh toán theo quy trình công ty.": "，用於後續 LinkedIn 投放與可選的搜尋廣告。我負責管理及協調後台金額；稅務與付款由會計依公司流程處理。",
"Chạy tuần đầu, review rồi chọn hướng tuần 2": "第一週執行，檢視後決定第二週方向",
"Tuần 1 chạy đúng plan. Cuối tuần, Bảo review dữ liệu để chọn hướng tuần 2 trong trần ngân sách đề xuất.": "第一週按計畫執行。我會在週末檢視數據，於提議的預算上限內決定第二週方向。",
"Bảo xác định vấn đề nằm ở tệp tiếp cận, phân phối, đo lường hay từng đoạn nội dung. Đoạn nào yếu thì thay đúng đoạn đó, giữ phần đang hiệu quả. Hai luồng VN tuần 1/tuần 2 và thư viện FDI giúp Bảo đổi nội dung linh hoạt; tệp chính và tệp dự phòng giúp chọn cách tiếp cận phù hợp. Mỗi luồng giữ đúng người đọc, ngôn ngữ và thông điệp.": "我會判斷問題出在受眾、投遞、衡量還是哪一段內容，針對薄弱環節替換，保留有效部分。本土企業的第一週、第二週兩組流程與外資素材庫提供內容調整空間；主要與備用名單則提供受眾選擇。每組流程都維持相符的讀者、語言與訊息。",
"Quy mô tệp sau lọc quyết định phạm vi thử ban đầu. Khi mức tiếp cận hạn chế hoặc dữ liệu còn mỏng, Bảo thu hẹp phép thử, quan sát thêm hoặc giữ lại ngân sách theo chất lượng tín hiệu và mức chi thực tế.": "初期測試範圍由篩選後的受眾規模決定。若觸及有限或數據較少，我會依訊號品質與實際花費，縮小測試、延長觀察或保留預算。",
"Đo gì để quyết định tiếp tục?": "看哪些數據，決定是否繼續？",
"Điều cần đánh giá": "評估項目",
"Dữ liệu theo dõi": "追蹤數據",
"Cách dùng khi review": "檢視時如何運用",
"Tiếp cận đúng doanh nghiệp và người phụ trách": "是否接觸到合適的企業與負責人",
"Phân phối theo công ty, chức năng và cấp bậc": "依公司、工作職能及職級查看投遞分布",
"Đối chiếu quảng cáo có tới đúng nhóm cần tiếp cận.": "確認廣告是否到達目標群體。",
"Có cơ hội thấy và chú ý": "是否有機會看見並產生關注",
"Reach, impressions, frequency, CTR và engagement": "觸及人數、曝光次數、頻率、點擊率（CTR）與互動",
"Đọc mức tiếp cận, lặp lại và quan tâm trong cùng kỳ.": "在同一期間內觀察觸及、重複曝光與關注程度。",
"Người quan tâm có đi tiếp": "有興趣的人是否繼續了解",
"Phiên có tương tác trên trang đọc và nội dung giải thích/case theo nguồn đo tương ứng": "依相應衡量來源，查看閱讀頁、說明內容及案例的互動工作階段",
"Chọn đoạn giúp người đọc tìm hiểu sâu hơn và đoạn cần điều chỉnh.": "判斷哪些環節促進深入了解，哪些需要調整。",
"Sử dụng tiền có hợp lý": "預算使用是否合理",
"Chi dashboard, CPM/CPC và ngân sách còn lại": "後台花費、CPM／CPC 與剩餘預算",
"Quyết định phần tiếp tục, điều chỉnh hoặc giữ lại.": "決定繼續投入、調整或保留的部分。",
"Lead đã xác minh là tín hiệu thương mại bổ sung. Bảo đọc kết quả cùng lượng dữ liệu và độ tin cậy của kỳ review, rồi gửi Vy nhận định và đề xuất bước tiếp theo.": "經確認的潛在客戶是補充的商業訊號。我會結合該期數據量與可信度解讀結果，再把判斷與下一步建議整理給你。",
"Ba điểm Vy xem giúp Bảo": "請你協助確認三點",
"1. Mức đầu tư": "1. 投資金額",
"Vy thấy trần 11,7 triệu đồng, chưa thuế, phù hợp để trình cho phương án này chứ?": "你覺得以 1,170 萬越南盾（未稅）作為這份方案的預算上限，適合提報嗎？",
"Bảo đề xuất giữ mức này để triển khai đợt đầu và có ngân sách cho bước tiếp theo theo kết quả thực tế.": "我建議採用這個額度，執行首輪後，仍有預算依實際結果安排下一步。",
"Vy có thể phản hồi:": "你可以回覆：",
"Đồng ý / Góp ý mức đầu tư / Đề nghị dừng phương án": "同意／建議調整金額／建議停止此方案",
"2. Cơ cấu sử dụng ngân sách": "2. 預算配置",
"Vy đồng ý cơ cấu 5,6 triệu cho đợt đầu và 6,1 triệu giữ lại trong cùng tổng ngân sách chứ?": "你同意首輪使用 560 萬越南盾，並在同一總預算內保留 610 萬越南盾的配置嗎？",
"Phần giữ lại gồm tối đa 5,6 triệu LinkedIn tiếp theo và tối đa 0,5 triệu Search. Bảo điều chỉnh cách sử dụng theo dữ liệu trong trần được duyệt.": "保留額度包含後續 LinkedIn 最多 560 萬越南盾，以及搜尋廣告最多 50 萬越南盾。我會依數據，在核准的上限內調整使用方式。",
"Đồng ý / Góp ý cơ cấu chi / Đề nghị đổi cơ cấu": "同意／提供配置建議／建議更改配置",
"3. Cách đánh giá hiệu quả": "3. 成效評估方式",
"Vy đồng ý đánh giá đợt đầu theo đúng tệp, mức quan tâm, hành vi đi tiếp và chi phí, với lead đã xác minh là tín hiệu bổ sung chứ?": "你同意首輪以受眾準確度、關注程度、後續了解行為與成本評估成效，並把經確認的潛在客戶作為補充訊號嗎？",
"Bảo dùng review cuối tuần 1 để chọn hướng tuần 2 và cách sử dụng ngân sách. Kết quả được đọc cùng độ tin cậy và lượng dữ liệu thực tế.": "我會依第一週末的檢視結果，決定第二週方向與預算使用方式，並結合實際數據量及可信度判讀。",
"Đồng ý / Góp ý tiêu chí đánh giá / Đề nghị đổi cách đánh giá": "同意／提供評估指標建議／建議更改評估方式",
"Logic quảng cáo và cách điều chỉnh theo dữ liệu · Digiwin": "廣告策略與數據調整邏輯 · Digiwin",
"Cách tiếp cận · Bảo gửi Vy": "受眾與內容策略",
"Logic quảng cáo và cách điều chỉnh theo dữ liệu": "廣告策略與數據調整邏輯",
"Bảo bắt đầu từ đúng doanh nghiệp và người phụ trách, chọn một vấn đề họ cần giải quyết, rồi nối quảng cáo với phần giải thích và case. Mục tiêu awareness là để Digiwin được nhớ đến khi doanh nghiệp cân nhắc giải pháp quản trị cho bài toán đó.": "我會先找合適的企業與負責人，選一個他們需要解決的問題，再串起廣告、說明與案例。品牌認知的目標，是讓企業在考慮該問題的管理解決方案時，能想到 Digiwin。",
"Nội dung trang": "本頁內容",
"Chọn tệp": "受眾篩選",
"Hai giả thuyết": "兩組內容假設",
"Ví dụ hình ảnh": "視覺示例",
"Mạch tiếp cận": "接觸流程",
"Quyết định theo dữ liệu": "數據與決策",
"1. Chọn doanh nghiệp, rồi chọn người cần tiếp cận": "1. 先選企業，再選需要接觸的人",
"Ưu tiên chuỗi cung ứng bán dẫn và điện tử: PCB, substrate, linh kiện, vật liệu đóng gói và gia công chính xác cho thiết bị. Với mỗi nhóm, Bảo xét bài toán quản trị và nơi có quyền quyết định hệ thống để chọn hướng tiếp cận.": "優先考慮半導體與電子供應鏈，包括 PCB、載板、零組件、封裝材料及設備精密加工。我會依各組企業的管理問題，以及系統決策權所在，選擇接觸方式。",
"LỚP 1": "第一層",
"Doanh nghiệp": "企業",
"Đối chiếu tên, website và Company Page để giảm nhầm định danh.": "核對公司名稱、網站與公司專頁，降低辨識錯誤。",
"LỚP 2": "第二層",
"Việt Nam": "越南地區",
"Khoanh phạm vi người làm việc tại thị trường cần tiếp cận.": "限定在目標市場工作的人員。",
"LỚP 3": "第三層",
"Chức năng": "工作職能",
"Chọn nhóm có trách nhiệm với vấn đề: vận hành, chất lượng, kỹ thuật hoặc IT.": "選擇與問題相關的職能：營運、品質、工程或 IT。",
"LỚP 4": "第四層",
"Cấp bậc": "職級",
"Thu hẹp tới nhóm quản lý có ảnh hưởng đến việc đánh giá giải pháp.": "進一步聚焦於能影響解決方案評估的管理人員。",
"Tệp chính · 424 dòng công ty cung cấp": "主要名單 · 公司提供的 424 筆資料",
"Bảo giữ danh sách nguồn, nghiên cứu và bổ sung định danh website/Page nhằm giúp LinkedIn nhận diện đúng công ty. Độ phù hợp với từng hướng quảng cáo được xét cùng hoạt động, vai trò và phân phối thực tế.": "我保留原始名單，研究並補上網站與專頁資訊，協助 LinkedIn 辨識正確公司。各企業是否適合特定廣告方向，會一併考量其業務、角色與實際投遞情況。",
"Tệp dự phòng · 52 Company Pages": "備用名單 · 52 個公司專頁",
"Từ 203 đơn vị được nghiên cứu riêng, Bảo giữ 52 Company Pages có căn cứ định danh. Đây là phương án bổ sung khi tệp chính gặp vấn đề về mapping hoặc quy mô tiếp cận sau lọc. Bảo chọn tệp theo chất lượng mapping, quy mô và phân phối thực tế.": "另行研究的 203 家單位中，我保留了 52 個有辨識依據的公司專頁。當主要名單的配對或篩選後規模有問題時，這份名單可作為補充。選用時仍依配對品質、受眾規模與實際投遞判斷。",
"Theo lần kiểm gần nhất 6–7/10, tệp chính đã gửi bản sửa và chờ đọc lại mapping/quy mô; backup hiển thị Ready, phần mapping chi tiết cần kiểm tiếp. Bước trước khi dùng là xác nhận đúng công ty và quy mô sau lọc.": "依 10 月 6–7 日最近一次檢查，主要名單已提交修正版，待回看配對結果與規模；備用名單顯示 Ready，詳細配對資訊仍需核對。使用前會確認公司辨識與篩選後規模。",
"Ngôn ngữ nội dung được chọn theo nhóm người đọc. Nhóm nội địa/FDI và vai trò công việc được đối chiếu riêng; ngôn ngữ hồ sơ LinkedIn chỉ là một phần của cấu hình tiếp cận.": "內容語言依實際讀者選擇。本土／外資身分與工作角色會分別核對；LinkedIn 個人檔案語言只是受眾設定的一部分。",
"2. Hai nhóm, hai giả thuyết nội dung": "2. 兩組受眾，兩組內容假設",
"Nội địa · Chuẩn bị đáp ứng khách hàng trong chuỗi": "本土企業 · 準備因應供應鏈客戶的要求",
"Giả thuyết: khi doanh nghiệp cần chuẩn bị cho yêu cầu đánh giá của khách hàng, nội dung về hồ sơ, quy trình và dữ liệu sẽ có ý nghĩa với người phụ trách. Bảo dùng ERP như cầu nối để chuẩn bị năng lực quản trị, rồi giải thích bằng cơ chế và case phù hợp.": "假設：企業準備接受客戶評估時，文件、流程與數據相關內容會對負責人有意義。我以 ERP 作為建立管理能力的橋梁，再透過合適的機制說明與案例，解釋如何準備。",
"Liên tưởng muốn xây: Digiwin hiểu việc chuẩn bị năng lực quản trị để doanh nghiệp Việt từng bước tham gia chuỗi cung ứng bán dẫn.": "希望建立的聯想：Digiwin 理解越南企業逐步參與半導體供應鏈時，需要準備哪些管理能力。",
"FDI · Giải quyết vấn đề vận hành cụ thể": "外資企業 · 解決具體營運問題",
"Giả thuyết: người phụ trách sẽ quan tâm hơn khi quảng cáo bắt đầu từ tình huống họ nhận ra, như kết quả test bất thường hoặc các bộ phận nhìn trạng thái lot khác nhau. Phần tiếp theo làm rõ dữ liệu cần đối chiếu, trách nhiệm và giá trị phối hợp.": "假設：從負責人熟悉的情境切入，更能引起關注，例如測試結果異常，或不同部門看到同一批次的狀態不同。後續內容說明應核對的數據、責任分工與協作價值。",
"Liên tưởng muốn xây: khi cần đánh giá giải pháp quản trị cho bài toán vận hành này, nghĩ đến Digiwin. Giá trị thể hiện qua thời gian, phối hợp và kiểm soát rủi ro.": "希望建立的聯想：評估這類營運問題的管理解決方案時，想到 Digiwin。價值透過時間、協作與風險控管呈現。",
"English và Chinese giữ cùng bài toán, mạch kể và phạm vi case; cách đặt câu, thuật ngữ và lời mời đọc tiếp được điều chỉnh cho người đọc của từng bản.": "英文與中文保留相同問題、敘事脈絡與案例適用範圍；句型、術語及繼續閱讀的邀請，則依各版本讀者調整。",
"3. Hình ảnh cùng kể một logic": "3. 視覺與內容傳達同一個邏輯",
"Logo Digiwin, nền sáng, xanh–navy và chất liệu có chiều sâu tạo sự nhất quán giữa các điểm chạm. Hồ sơ, linh kiện và đường nối dữ liệu giúp thể hiện câu hỏi vận hành: cần chuẩn bị gì, đối chiếu gì và ai chịu trách nhiệm. Cảnh thay đổi theo ý cần giải thích.": "Digiwin 標誌、淺色背景、藍與海軍藍，以及具層次感的材質，讓各接觸點保持一致。文件、零組件與數據連線呈現營運問題：需要準備什麼、核對什麼、由誰負責。畫面則隨說明重點調整。",
"Điểm xuyên suốt là chuyên môn quản trị gắn với ngành: mỗi quảng cáo giúp người đọc nhìn rõ một vấn đề và cách tiếp cận của Digiwin. Thông điệp, hình ảnh, case và trang đọc cùng phục vụ một người đọc và một bài toán.": "貫穿內容的是與產業相關的管理專業：每則廣告幫助讀者看清一個問題，以及 Digiwin 的處理思路。訊息、視覺、案例與閱讀頁，都圍繞同一位讀者及同一個問題。",
"Ví dụ VN · Từ năng lực quản trị đến hồ sơ đánh giá": "本土企業示例 · 從管理能力到評估文件",
"Người đọc: quản lý nhà máy hoặc chất lượng tại doanh nghiệp nội địa đang chuẩn bị đáp ứng khách hàng trong chuỗi. Mạch nội dung đi từ lời mời chuẩn bị năng lực quản trị tới hồ sơ cần đối chiếu, rồi case có cơ chế cụ thể.": "讀者：本土企業中，正準備因應供應鏈客戶要求的工廠或品質主管。內容從管理能力準備，延伸到需要核對的文件，再以具體案例說明機制。",
"Mở đầu · Vì sao Digiwin liên quan?": "開場 · 為什麼與 Digiwin 有關？",
"Hồ sơ và linh kiện công nghiệp nối kinh nghiệm Digiwin với nhu cầu chuẩn bị quản trị của doanh nghiệp Việt.": "以文件與工業零組件，連結 Digiwin 經驗和越南企業的管理準備需求。",
"Giải thích · Chuẩn bị cho yêu cầu nào?": "說明 · 要為哪些要求做準備？",
"Câu hỏi về hồ sơ audit đưa mục tiêu tham gia chuỗi về một tình huống quản trị người phụ trách cần chuẩn bị.": "用稽核文件的問題，將參與供應鏈的目標落到負責人需要準備的管理情境。",
"Case · Cơ chế được minh họa ra sao?": "案例 · 如何呈現具體機制？",
"Case Aplus Semiconductor tại Trung Quốc minh họa truy xuất lịch sử theo serial, trong giải pháp DigiHua iMES + TOP GP.": "中國 Aplus Semiconductor 案例，以 DigiHua iMES + TOP GP 解決方案，說明依序號追溯產品歷史的機制。",
"Ý muốn người đọc giữ lại: chuẩn bị đáp ứng khách hàng bắt đầu từ khả năng tổ chức và đối chiếu dữ liệu. ERP hỗ trợ năng lực quản trị; việc đánh giá nhà cung ứng theo yêu cầu cụ thể của khách hàng.": "希望讀者記住：因應客戶要求，從整理與核對數據的能力開始。ERP 支援管理能力的建立；供應商評估則依各客戶的具體要求進行。",
"Xem toàn luồng": "查看完整廣告流程（原文）",
"Đọc case": "閱讀案例（原文）",
"Ví dụ FDI · Đối chiếu kết quả theo lot": "外資企業示例 · 按批次核對結果",
"Người đọc: Quality phối hợp Operations tại nhà máy đóng gói và kiểm thử. Giả thuyết là một câu hỏi sát công việc sẽ tạo chú ý; phần giải thích và case giúp người quan tâm hiểu giá trị của việc nối dữ liệu và trách nhiệm.": "讀者：封裝測試工廠的品質人員，以及協作的營運人員。假設是貼近工作的問題能引起注意；後續說明與案例，則幫助有興趣的人理解串連數據與責任的價值。",
"Mở đầu · Gọi đúng tình huống": "開場 · 點出熟悉的情境",
"Kết quả test bất thường dẫn tới câu hỏi về lot, thời điểm test và người phụ trách hồ sơ.": "測試結果異常，帶出對批次、測試時間與紀錄負責人的核對。",
"Giải thích · Chỉ rõ bước đối chiếu": "說明 · 指出核對步驟",
"Hình lot nối với các hồ sơ giải thích quan hệ dữ liệu cần kiểm khi lot được tách hoặc gộp.": "以批次連結相關紀錄，說明分批或合批時需要確認的數據關係。",
"Case · Đưa cơ chế vào bối cảnh thực": "案例 · 放回實際導入情境",
"Case 江苏中科智芯集成科技有限公司 tại Trung Quốc dùng Digiwin ERP + iMES; phần MES nối dữ liệu truy vết và ghi nhận ngoại lệ.": "中國的 江苏中科智芯集成科技有限公司 案例採用 Digiwin ERP + iMES；其中 MES 串連追溯數據並記錄異常。",
"Giá trị muốn làm rõ: Quality và Operations có cơ sở chung để phối hợp bước kiểm tiếp theo. Case giúp giải thích cơ chế trong bối cảnh triển khai cụ thể.": "希望說明的價值：品質與營運有共同依據，協作決定下一步檢查。案例則在具體導入情境中解釋這套機制。",
"4. Mỗi điểm chạm có một nhiệm vụ": "4. 每個接觸點都有明確任務",
"Ảnh đơn · Tạo chú ý": "單圖廣告 · 引起注意",
"Đặt một vấn đề rõ với người đọc mới; nhận diện Digiwin và bài toán ngay trong quảng cáo.": "向新讀者提出明確問題，讓人從廣告就能辨識 Digiwin 與議題。",
"Carousel · Giải thích sâu": "輪播廣告 · 深入說明",
"Khi tệp tương tác với chính quảng cáo mới đủ điều kiện, nối câu hỏi ban đầu với cách đối chiếu và case phù hợp.": "與這批新廣告互動的受眾達到條件後，將起初的問題連結到核對方式與合適案例。",
"Trang đọc · Củng cố cơ sở": "閱讀頁 · 補足判斷依據",
"Giúp người muốn tìm hiểu xem bối cảnh triển khai, cơ chế giải pháp và bước trao đổi nhu cầu.": "讓有興趣的人了解導入背景、解決機制，以及如何進一步交流需求。",
"Mỗi điểm chạm tự có ngữ cảnh; các phần cùng giữ người đọc, vấn đề và nhận diện Digiwin. Hai luồng VN và thư viện FDI cho phép Bảo thay đúng đoạn cần cải thiện, giữ mạch nội dung của cả luồng.": "各接觸點本身都有完整語境，同時維持一致的讀者、問題與 Digiwin 識別。兩組越南文流程與外資素材庫，讓我能替換需要改善的環節，維持整體內容脈絡。",
"5. Dữ liệu dẫn đến quyết định nào?": "5. 數據如何轉成決策？",
"Tuần 1 chạy đúng plan. Cuối tuần, Bảo đọc dữ liệu theo tệp, quảng cáo và cùng kỳ quan sát để chọn hướng tuần 2 trong trần ngân sách. Thay đổi bám vào nguyên nhân của từng khâu.": "第一週按計畫執行。週末依受眾、廣告及同一觀察期間的數據，於預算上限內決定第二週方向。調整會對應各環節的原因。",
"Review cuối tuần 1 → lựa chọn tuần 2": "第一週末檢視 → 第二週選擇",
"Tín hiệu quan sát": "觀察到的訊號",
"Hướng xử lý của Bảo": "我的調整方式",
"Đo lường thiếu hoặc lệch nguồn": "衡量資料缺漏或來源不一致",
"Đối soát cách đo và nguồn dữ liệu trước khi đánh giá nội dung.": "先核對衡量方式與數據來源，再評估內容。",
"Phân phối lệch công ty hoặc vai trò": "投遞的公司或職務偏離目標",
"Rà mapping và bộ lọc; cân nhắc tệp chính/backup theo dữ liệu tương ứng.": "檢查配對與篩選條件，依相應數據考慮主要或備用名單。",
"Reach thấp, lặp lại hoặc nhịp chi chưa phù hợp": "觸及低、重複曝光或花費節奏不合適",
"Kiểm quy mô sau lọc, cấu hình và pacing; điều chỉnh phân phối trong ngân sách.": "檢查篩選後規模、設定與花費節奏，在預算內調整投遞。",
"Đúng tệp, quảng cáo mở đầu ít tạo chú ý": "受眾正確，但開場廣告吸引力不足",
"Thay hook hoặc visual mở đầu phù hợp cùng persona và ngôn ngữ.": "維持相同讀者與語言，調整開場切入點或視覺。",
"Có quan tâm ban đầu, bước tìm hiểu tiếp yếu": "已有初步興趣，但後續了解行為偏弱",
"Rà mạch chuyển tiếp; thay đúng phần giải thích, case hoặc trang đọc cần cải thiện.": "檢查內容銜接，替換需要改善的說明、案例或閱讀頁。",
"Tín hiệu tốt và tệp tương tác đủ điều kiện": "訊號良好，互動受眾也達到投放條件",
"Tiếp tục phần hiệu quả; dùng carousel RMK phù hợp với nhóm đã tương tác.": "延續有效部分，向已互動受眾投放合適的輪播再行銷廣告。",
"Dữ liệu còn mỏng hoặc độ phủ hạn chế": "數據仍少或涵蓋範圍有限",
"Quan sát thêm, thu hẹp phép thử hoặc giữ lại ngân sách theo chất lượng tín hiệu.": "依訊號品質，延長觀察、縮小測試或保留預算。",
"Reach và tần suất cho biết cơ hội tiếp xúc; CTR, engagement và hành vi đi tiếp giúp đọc mức quan tâm. Liên tưởng về Digiwin là mục tiêu awareness cần được đánh giá riêng qua phản hồi hoặc phép đo phù hợp. Lead đã xác minh bổ sung tín hiệu thương mại.": "觸及與頻率反映接觸機會；CTR、互動與後續行為反映關注程度。對 Digiwin 的品牌聯想，則需要透過回饋或合適衡量方式另行評估。經確認的潛在客戶提供補充的商業訊號。",
"Mỗi lần điều chỉnh, Bảo ghi rõ tín hiệu, phần thay và kết quả lần review sau. Khi đổi hook, Bảo ưu tiên giữ cùng tệp, thông điệp và phần giải thích để đọc tác động; đổi nhiều yếu tố cùng lúc được đánh giá theo toàn bộ thay đổi.": "每次調整，我都記錄訊號、替換部分，以及下一次檢視的結果。更換開場切入點時，優先維持相同受眾、訊息與說明，方便判讀影響；若同時更動多個因素，則依整體變更評估。",
"Bảo quyết định tệp, nội dung và nhịp chạy trong phạm vi được giao. Phần đầu tư giữ ba điểm Vy xem giúp: mức ngân sách, cơ cấu chi và cách đánh giá hiệu quả.": "我在授權範圍內決定受眾、內容與投放節奏。投資部分請你協助確認三點：預算金額、配置與成效評估方式。",
"Xem 3 điểm đầu tư": "查看三項投資確認事項",
"Mail gửi Vy · Digiwin": "郵件草稿 · Digiwin",
"Mail gửi Vy": "郵件草稿",
"Tiêu đề:": "主旨：",
"Đề xuất paid ads chuỗi cung ứng bán dẫn – ngân sách 11,7 triệu chưa thuế": "半導體供應鏈廣告提案 — 預算 1,170 萬越南盾（未稅）",
"Vy ơi,": "你好，",
"Bảo gửi Vy phương án paid ads cập nhật cho nhóm doanh nghiệp trong chuỗi cung ứng bán dẫn và điện tử. Hướng nội dung tách riêng: tiếng Việt tập trung vào chuẩn bị năng lực quản trị để tham gia chuỗi; English/Chinese mở từ vấn đề vận hành và giá trị đối với người phụ trách ở doanh nghiệp FDI.": "我把半導體與電子供應鏈企業的廣告方案更新好了，整理給你參考。內容分成兩個方向：越南文著重於參與供應鏈所需的管理能力準備；英文與中文則從外資企業負責人的營運問題及相關價值切入。",
"Bảo đề xuất tổng ngân sách tối đa": "我建議的總預算上限是",
": 5,6 triệu cho đợt LinkedIn đầu; 6,1 triệu giữ lại trong cùng tổng ngân sách, gồm tối đa 5,6 triệu LinkedIn tiếp theo và 0,5 triệu Search tùy chọn. Bảo theo dõi số tiền trên dashboard, kế toán xử lý thuế và thanh toán theo quy trình công ty.": "：首輪 LinkedIn 使用 560 萬越南盾；同一總額內保留 610 萬越南盾，包含後續 LinkedIn 最多 560 萬，以及可選的搜尋廣告 50 萬。我追蹤後台金額，稅務與付款由會計依公司流程處理。",
"Tuần 1 Bảo chạy đúng plan, review cuối tuần rồi chọn hướng tuần 2 theo dữ liệu. Bảo đã có hai luồng VN, thư viện FDI và tệp chính/dự phòng để thay đúng đoạn cần cải thiện, giữ phần đang hiệu quả.": "第一週我會按計畫執行，週末檢視後，再依數據決定第二週方向。兩組越南文流程、外資素材庫，以及主要與備用名單都已備妥，可以針對需要改善的環節替換，保留有效部分。",
"Bảo bổ sung phần logic quảng cáo để Vy xem cách chọn tệp chính/dự phòng, giả thuyết riêng cho VN–FDI và hai ví dụ nối hình ảnh với thông điệp. Phần này cũng chỉ rõ dữ liệu nào dẫn đến điều chỉnh tuần 2.": "我也補上廣告策略，說明主要與備用名單的選擇方式、本土與外資企業的不同假設，以及兩組視覺與訊息如何銜接的示例。這一頁也列出哪些數據會帶來第二週的調整。",
"Vy mở": "你可以開啟",
"BAT_DAU.html": "提案首頁",
"trong thư mục để xem đề xuất, logic quảng cáo, demo nội dung và file theo dõi. Bảo nhờ Vy xem giúp ba điểm để tổng hợp, trình lãnh đạo:": "，查看提案、廣告策略、內容示例與追蹤表。請你協助看一下三點，方便彙整後向主管提報：",
"Trần đầu tư 11,7 triệu đồng, chưa thuế.": "投資上限 1,170 萬越南盾（未稅）。",
"Cơ cấu 5,6 triệu đợt đầu và 6,1 triệu giữ lại trong cùng tổng ngân sách.": "首輪 560 萬越南盾，並在同一總預算內保留 610 萬越南盾。",
"Đánh giá theo đúng tệp, mức quan tâm, hành vi đi tiếp và chi phí; lead đã xác minh là tín hiệu bổ sung.": "依受眾準確度、關注程度、後續了解行為與成本評估，經確認的潛在客戶作為補充訊號。",
"Vy phản hồi đồng ý hoặc góp ý ngay dưới từng điểm giúp Bảo nhé. Bảo phụ trách triển khai và gửi Vy kết quả cùng đề xuất sau review tuần đầu.": "麻煩你在各項下方回覆是否同意，或直接留下建議。我負責執行，並在第一週檢視後，把結果與下一步建議整理給你。",
"Cảm ơn Vy,": "謝謝你！",
"Demo nội dung · Digiwin": "內容示例 · Digiwin",
"Xem": "查看",
"logic quảng cáo": "廣告策略與假設",
"để hiểu cách chọn tệp, vai trò từng nội dung và hướng điều chỉnh theo dữ liệu.": "，了解受眾選擇、各段內容的任務與數據調整方式。",
"Nội dung đại diện": "代表內容",
"Hai luồng để Vy xem cách tiếp cận": "用兩組流程看整體接觸方式",
"Một luồng VN về chuẩn bị năng lực quản trị và một luồng FDI về đối chiếu dữ liệu chất lượng. Mỗi luồng gồm ảnh đơn, carousel giải thích, case và trang đọc.": "一組越南文流程說明管理能力準備；另一組外資企業流程說明品質數據核對。每組都包含單圖、說明輪播、案例與閱讀頁，以下開啟的是原文廣告素材。",
"Tiếng Việt · 10 ảnh": "越南文 · 10 張圖",
"Nội địa · Chuẩn bị năng lực quản trị": "本土企業 · 管理能力準備",
"VN tuần 1": "越南文 · 第一週",
"Xem luồng nội dung": "查看廣告流程（原文）",
"English · 10 ảnh": "英文 · 10 張圖",
"Quality · Đối chiếu kết quả theo lot": "品質 · 按批次核對結果",
"FDI · Quality": "外資企業 · 品質",
"Xem các chủ đề và ngôn ngữ khác": "查看其他主題與語言",
"Thư viện nội dung · Digiwin": "素材庫 · Digiwin",
"Nội dung theo nhóm người đọc": "依讀者分組的內容",
"Thư viện để chọn và thay đúng đoạn": "選用素材，調整需要改善的環節",
"Hai luồng VN tuần 1/tuần 2 và các chủ đề OSAT cho FDI. Bảo chọn nội dung theo vấn đề của kỳ review, người phụ trách và ngôn ngữ phù hợp.": "包含越南文第一週／第二週的兩組流程，以及外資企業的 OSAT 主題。我會依當期檢視發現的問題、負責人與合適語言選擇內容。素材保留原文，可依下方語言分類查看。",
"Tất cả": "全部",
"Tiếng Việt": "越南文",
"English": "英文",
"中文 giản thể": "簡體中文",
"中文 phồn thể": "繁體中文",
"Nội địa · Chuẩn bị hệ thống và tiến độ": "本土企業 · 系統與時程準備",
"VN tuần 2": "越南文 · 第二週",
"中文 giản thể · 10 ảnh": "簡體中文 · 10 張圖",
"中文 phồn thể · 10 ảnh": "繁體中文 · 10 張圖",
"Operations · Theo dõi vận hành theo lot": "營運 · 按批次追蹤作業狀態",
"FDI · Operations": "外資企業 · 營運",
"Quality · Ba câu hỏi để đối chiếu kết quả": "品質 · 核對結果的三個問題",
"FDI · Quality phối hợp Operations": "外資企業 · 品質與營運協作",
"Operations · Ba câu hỏi trước bàn giao": "營運 · 交接前的三個問題",
"FDI · Operations phối hợp Quality": "外資企業 · 營運與品質協作",
"Operations và Finance · Hồ sơ cuối kỳ": "營運與財務 · 期末紀錄",
"FDI · Operations phối hợp Finance": "外資企業 · 營運與財務協作",
"Ảnh đối chiếu kế hoạch quảng cáo": "廣告計畫佐證截圖",
"Hồ sơ tham khảo · LinkedIn & Google": "參考資料 · LinkedIn 與 Google",
"Các ảnh chụp giúp đối chiếu tệp khách hàng, cách thu hẹp audience và kết quả tra cứu từ khóa. Chọn ảnh để xem lớn và đọc rõ nội dung.": "這些截圖用於核對企業名單、受眾篩選方式與關鍵字查詢結果。點選圖片可放大閱讀；截圖保留原始介面語言。",
"10 ảnh chụp": "10 張截圖",
"30/09–07/10/2026": "2026/09/30–10/07",
"Tệp khách hàng · Bộ lọc · Từ khóa": "企業名單 · 篩選條件 · 關鍵字",
"Nhóm bằng chứng": "佐證分類",
"Tệp chính": "主要名單",
"Tệp dự phòng & bộ lọc": "備用名單與篩選條件",
"Keyword Planner": "關鍵字規劃工具",
"Tệp chính 424 công ty": "主要名單 · 424 筆公司資料",
"Đối chiếu tên tệp đã lưu và trạng thái xử lý trên LinkedIn ngày 06/10/2026.": "核對 2026/10/06 LinkedIn 上已儲存的名單名稱與處理狀態。",
"LinkedIn Campaign Manager · 06/10/2026": "LinkedIn Campaign Manager · 2026/10/06",
"Tệp 424 công ty đã lưu": "已儲存的 424 筆公司名單",
"Tên tệp hiển thị trên LinkedIn khớp bản 424 công ty đã bổ sung định danh.": "LinkedIn 顯示的名單名稱，與已補上辨識資訊的 424 筆版本一致。",
"Xem ảnh lớn": "放大圖片",
"↗": "↗",
"Trạng thái xử lý: Updating": "處理狀態：Updating",
"LinkedIn hiển thị Updating. Mức 80% trên ảnh là số cũ trong lúc hệ thống xử lý bản thay thế.": "LinkedIn 顯示 Updating。系統正在處理替換版本，畫面上的 80% 是先前的數值。",
"Tệp dự phòng 52 công ty và bộ lọc": "52 家公司的備用名單與篩選條件",
"Số thành viên dưới đây là ước tính của LinkedIn trong lần kiểm tra ngày 07/10/2026.": "以下人數為 2026/10/07 檢查時，LinkedIn 顯示的估計值。",
"LinkedIn Campaign Manager · 07/10/2026": "LinkedIn Campaign Manager · 2026/10/07",
"Tệp dự phòng đã ở trạng thái Ready": "備用名單顯示 Ready",
"Màn hình hiển thị Ready, tỷ lệ khớp >90% và 444.274 thành viên. Phần chi tiết vẫn hiện 0 Companies, Matched(0), Unmatched(0), chưa có hàng công ty để đối soát.": "畫面顯示 Ready、配對率 >90%，以及 444,274 位成員。詳細資訊仍顯示 0 Companies、Matched(0)、Unmatched(0)，尚無公司資料列可供核對。",
"Chọn đúng tệp công ty dự phòng": "選取正確的備用公司名單",
"Bộ lọc chọn Company List R5-52. Đây là tệp nền để tiếp tục thu hẹp theo vai trò và cấp bậc.": "篩選條件選用 Company List R5-52，再以此為基礎，依工作角色與職級縮小受眾。",
"Thu hẹp theo chức năng công việc": "依工作職能縮小受眾",
"Giữ người thuộc tệp công ty và làm một trong bốn chức năng: Engineering, Information Technology, Operations hoặc Quality Assurance.": "保留名單內企業的人員，且工作職能屬於工程、資訊技術、營運或品質保證其中一項。",
"Ước tính với ngôn ngữ English": "語言設為 English 時的估計人數",
"Màn hình hiển thị 460 thành viên với địa bàn Việt Nam và ngôn ngữ English. Phần hướng dẫn của LinkedIn cho biết lựa chọn English có thể tiếp cận cả hồ sơ dùng ngôn ngữ khác, ngoại trừ Sponsored Messaging.": "地區設為越南、語言設為 English 時，畫面顯示 460 位成員。當時 LinkedIn 的說明指出，English 設定可涵蓋使用其他個人檔案語言的人員，Sponsored Messaging 除外。",
"Đối chiếu với ngôn ngữ Vietnamese": "對照語言設為 Vietnamese 的結果",
"Khi chuyển sang Vietnamese ở bước lọc cuối, màn hình hiển thị dưới 300 thành viên tại Việt Nam.": "在最後篩選步驟改為 Vietnamese 後，畫面顯示越南地區少於 300 位成員。",
"Kết quả tra cứu Keyword Planner": "關鍵字規劃工具查詢結果",
"Cấu hình: Việt Nam · Google · 09/2025–08/2026. Dấu gạch ngang thể hiện chỉ số không được hiển thị trong truy vấn này; không thể diễn giải thành nhu cầu bằng 0.": "設定：越南 · Google · 2025/09–2026/08。橫線表示這次查詢未顯示指標，不能據此解讀為需求等於零。",
"Google Keyword Planner · 30/09/2026": "Google Keyword Planner · 2026/09/30",
"Tra cứu bằng tiếng Anh": "英文查詢",
"Bảy từ khóa trong cấu hình English đều hiển thị dấu gạch ngang tại các cột chỉ số.": "English 設定下的七個關鍵字，各指標欄位都顯示橫線。",
"Tra cứu bằng tiếng Trung giản thể": "簡體中文查詢",
"Bảy từ khóa trong cấu hình Chinese (simplified) đều hiển thị dấu gạch ngang tại các cột chỉ số.": "Chinese (simplified) 設定下的七個關鍵字，各指標欄位都顯示橫線。",
"Tra cứu bằng tiếng Trung phồn thể": "繁體中文查詢",
"Bảy từ khóa trong cấu hình Chinese (traditional) đều hiển thị dấu gạch ngang tại các cột chỉ số.": "Chinese (traditional) 設定下的七個關鍵字，各指標欄位都顯示橫線。",
"Bảo · Hồ sơ tham khảo kế hoạch quảng cáo · 08/10/2026": "廣告計畫參考資料 · 2026/10/08",
"Cỡ gốc": "原始尺寸",
"Vừa khung": "符合視窗",
"Đóng ×": "關閉 ×",
}

ALTS = {
"Quảng cáo VN mở đầu: Digiwin đồng hành cùng doanh nghiệp Việt chuẩn bị năng lực quản trị để bước vào chuỗi bán dẫn.": "越南文開場廣告：Digiwin 陪伴越南企業準備管理能力，逐步參與半導體供應鏈。",
"Quảng cáo VN đặt câu hỏi: Khách hàng yêu cầu audit. Hồ sơ đã sẵn sàng?": "越南文廣告提出問題：客戶要求稽核，文件準備好了嗎？",
"Ảnh case Aplus tại Trung Quốc: báo công theo serial hỗ trợ truy xuất lịch sử từng sản phẩm.": "中國 Aplus 案例：依序號報工，支援追溯各產品的歷史紀錄。",
"Quảng cáo English cho Quality: Unexpected test result? Start with the lot.": "英文品質廣告：測試結果異常？從批次開始核對。",
"Card English Start with the right lot, minh họa các quan hệ giữa lot và hồ sơ liên quan.": "英文圖卡以正確批次為起點，呈現批次與相關紀錄的關係。",
"Card case Trung Quốc nêu cơ chế MES nối batch, workstation, operator và product/material để truy vết.": "中國案例圖卡：MES 串連批次、工站、人員與產品／物料，以支援追溯。",
"Digiwin với hook 200+ doanh nghiệp bán dẫn đã lựa chọn chúng tôi; đồng hành cùng doanh nghiệp Việt chuẩn bị quản trị. Minh họa linh kiện kim loại và hồ sơ quy trình.": "越南文 Digiwin 廣告以逾 200 家半導體企業的選擇為開場，連結越南企業的管理準備；畫面包含金屬零組件與流程文件。",
"Digiwin: 3 điểm cần chuẩn bị trước yêu cầu đánh giá Đúng phiên bản · Rõ phê duyệt · Có dữ liệu Chúng tôi đồng hành cùng doanh nghiệp Việt chuẩn bị năng lực quản trị để bước vào chuỗi bán dẫn.": "越南文 Digiwin 廣告：評估前的三項準備——版本正確、核准明確、有數據，協助企業準備參與半導體供應鏈的管理能力。",
"Illustration: Unexpected test result? Start with the lot.": "示意圖：測試結果異常？從批次開始核對。",
"示意图：测试结果异常，先核对哪一批？": "示意圖：測試結果異常，先核對哪一批？",
"示意圖：測試結果異常，先核對哪一批？": "示意圖：測試結果異常，先核對哪一批？",
"Illustration: Same lot. Different status reports?": "示意圖：同一批次，狀態報告為何不同？",
"示意图：同一批次，状态报告为何不同？": "示意圖：同一批次，狀態報告為何不同？",
"示意圖：同一批次，狀態報告為何不同？": "示意圖：同一批次，狀態報告為何不同？",
"Illustration: Unusual test results. Which records?": "示意圖：測試結果異常，該核對哪些紀錄？",
"示意图：测试结果异常，正在复核哪些记录？": "示意圖：測試結果異常，正在複核哪些紀錄？",
"示意圖：測試結果異常，正在複核哪些紀錄？": "示意圖：測試結果異常，正在複核哪些紀錄？",
"Illustration: blank calendar, production folders and packaged chips frame the month-end records question for plant operations.": "示意圖：空白日曆、生產資料夾與封裝晶片托盤，呈現工廠月底核對紀錄的問題。",
"示意图：空白日历、生产文件夹和封装芯片托盘呈现工厂月末记录核对问题。": "示意圖：空白日曆、生產資料夾與封裝晶片托盤，呈現工廠月底核對紀錄的問題。",
"示意圖：空白日曆、生產資料夾與封裝晶片托盤，呈現工廠月底核對紀錄的問題。": "示意圖：空白日曆、生產資料夾與封裝晶片托盤，呈現工廠月底核對紀錄的問題。",
}
